/**************************************************************************
 *
 *       Copyright (c) 2005-2016 by iCatch Technology, Inc.
 *
 *  This software is copyrighted by and is the property of iCatch
 *  Technology, Inc.. All rights are reserved by iCatch Technology, Inc..
 *  This software may only be used in accordance with the corresponding
 *  license agreement. Any unauthorized use, duplication, distribution,
 *  or disclosure of this software is expressly forbidden.
 *
 *  This Copyright notice MUST not be removed or modified without prior
 *  written consent of iCatch Technology, Inc..
 *
 *  iCatch Technology, Inc. reserves the right to modify this software
 *  without notice.
 *
 *  iCatch Technology, Inc.
 *  19-1, Innovation First Road, Science-Based Industrial Park,
 *  Hsin-Chu, Taiwan.
 *                                                                        *
 *                                                                        *
 **************************************************************************/
#ifndef __SP5K_CDSP_API_H__
#define __SP5K_CDSP_API_H__

#include "middleware/cdsp_def.h"

/**************************************************************************
 *                           C O N S T A N T S                            *
 **************************************************************************/
#define SP5K_IQ_CFG_REDO_POS_AFTER 		IQ_CFG_REDO_POS_AFTER
#define SP5K_IQ_CFG_REDO_POS_BEFORE 	IQ_CFG_REDO_POS_BEFORE

/*************************************************/
/*                5330 new api                   */
/*************************************************/

typedef enum sp5kIqBlocklSelector_e {
	SP5K_IQ_BLOCK_DARK_SUB          = 0,
	SP5K_IQ_BLOCK_OB,
	SP5K_IQ_BLOCK_WB_OFS,
	SP5K_IQ_BLOCK_BP,
	SP5K_IQ_BLOCK_BINNING_COR,
	SP5K_IQ_BLOCK_WB_PRE_GAIN,
	SP5K_IQ_BLOCK_LSC,
	SP5K_IQ_BLOCK_CA,
	SP5K_IQ_BLOCK_ARD,
	SP5K_IQ_BLOCK_ARD_MULTI_THR_EN,
	SP5K_IQ_BLOCK_ARD_CORNER_DENOISE,
	SP5K_IQ_BLOCK_DEPEAK_R,
	SP5K_IQ_BLOCK_DEPEAK_G,
	SP5K_IQ_BLOCK_DEPEAK_B,
	SP5K_IQ_BLOCK_WB_GAIN,
	SP5K_IQ_BLOCK_WB_GAIN2,
	SP5K_IQ_BLOCK_GLOBAL_GAIN,
	SP5K_IQ_BLOCK_RGB_DENOISE_R,
	SP5K_IQ_BLOCK_RGB_DENOISE_G,
	SP5K_IQ_BLOCK_RGB_DENOISE_B,
	SP5K_IQ_BLOCK_WHITE_CLIP1,
	SP5K_IQ_BLOCK_DARK_CLIP1,
	SP5K_IQ_BLOCK_CM,
	SP5K_IQ_BLOCK_RGB_GAMMA,
	SP5K_IQ_BLOCK_3D_LUT,
	SP5K_IQ_BLOCK_WHITE_CLIP2,
	SP5K_IQ_BLOCK_DARK_CLIP2,
	SP5K_IQ_BLOCK_CM2,
	SP5K_IQ_BLOCK_HUE,
	SP5K_IQ_BLOCK_Y_GAMMA,
	SP5K_IQ_BLOCK_WDR,
	SP5K_IQ_BLOCK_AA,
	SP5K_IQ_BLOCK_AHD,
	SP5K_IQ_BLOCK_AHD_Y_CORNER_DENOISE,
	SP5K_IQ_BLOCK_AHD_UV_CORNER_DENOISE,
	SP5K_IQ_BLOCK_YEF,
	SP5K_IQ_BLOCK_YNF,
	SP5K_IQ_BLOCK_Y_EDGE,
	SP5K_IQ_BLOCK_Y_CORNER_EDGE,
	SP5K_IQ_BLOCK_UV_LPF_COR,
	SP5K_IQ_BLOCK_UV_LPF_AREA,
	SP5K_IQ_BLOCK_UV_LPF_EDGE,
	SP5K_IQ_BLOCK_YUV_DEPEAK,
	SP5K_IQ_BLOCK_DIGITAL_EFFECT_X,
	SP5K_IQ_BLOCK_DIGITAL_EFFECT_Y,
	SP5K_IQ_BLOCK_PURPLE_FRING,

	SP5K_IQ_BLOCK_TEMPORAL_DN,
	SP5K_IQ_BLOCK_LDC,

	SP5K_IQ_BLOCK_REDO_HUE,
	SP5K_IQ_BLOCK_REDO_Y_GAMMA,
	SP5K_IQ_BLOCK_REDO_WDR,
	SP5K_IQ_BLOCK_REDO_AA,
	SP5K_IQ_BLOCK_REDO_AHD,
	SP5K_IQ_BLOCK_REDO_AHD_Y_CORNER_DENOISE,
	SP5K_IQ_BLOCK_REDO_AHD_UV_CORNER_DENOISE,
	SP5K_IQ_BLOCK_REDO_YEF,
	SP5K_IQ_BLOCK_REDO_YNF,
	SP5K_IQ_BLOCK_REDO_Y_EDGE,
	SP5K_IQ_BLOCK_REDO_Y_CORNER_EDGE,
	SP5K_IQ_BLOCK_REDO_UV_LPF_COR,
	SP5K_IQ_BLOCK_REDO_UV_LPF_AREA,
	SP5K_IQ_BLOCK_REDO_UV_LPF_EDGE,
	SP5K_IQ_BLOCK_REDO_YUV_DEPEAK,
	SP5K_IQ_BLOCK_REDO_DIGITAL_EFFECT_X,
	SP5K_IQ_BLOCK_REDO_DIGITAL_EFFECT_Y,
	SP5K_IQ_BLOCK_REDO_PURPLE_FRING,

	SP5K_IQ_BLOCK_SDO_HUE,
	SP5K_IQ_BLOCK_SDO_Y_GAMMA,
	SP5K_IQ_BLOCK_SDO_WDR,
	SP5K_IQ_BLOCK_SDO_AA,
	SP5K_IQ_BLOCK_SDO_AHD,
	SP5K_IQ_BLOCK_SDO_YEF,
	SP5K_IQ_BLOCK_SDO_YNF,
	SP5K_IQ_BLOCK_SDO_Y_EDGE,
	SP5K_IQ_BLOCK_SDO_Y_CORNER_EDGE,
	SP5K_IQ_BLOCK_SDO_UV_LPF_COR,
	SP5K_IQ_BLOCK_SDO_UV_LPF_AREA,
	SP5K_IQ_BLOCK_SDO_UV_LPF_EDGE,
	SP5K_IQ_BLOCK_SDO_YUV_DEPEAK,
	SP5K_IQ_BLOCK_SDO_DIGITAL_EFFECT_X,
	SP5K_IQ_BLOCK_SDO_DIGITAL_EFFECT_Y,
	SP5K_IQ_BLOCK_SDO_PURPLE_FRING,

	SP5K_IQ_BLOCK_S2DO_HUE,
	SP5K_IQ_BLOCK_S2DO_Y_GAMMA,
	SP5K_IQ_BLOCK_S2DO_WDR,
	SP5K_IQ_BLOCK_S2DO_AA,
	SP5K_IQ_BLOCK_S2DO_YEF,
	SP5K_IQ_BLOCK_S2DO_YNF,
	SP5K_IQ_BLOCK_S2DO_Y_EDGE,
	SP5K_IQ_BLOCK_S2DO_Y_CORNER_EDGE,
	SP5K_IQ_BLOCK_S2DO_UV_LPF_COR,
	SP5K_IQ_BLOCK_S2DO_UV_LPF_AREA,
	SP5K_IQ_BLOCK_S2DO_UV_LPF_EDGE,
	SP5K_IQ_BLOCK_S2DO_YUV_DEPEAK,
	SP5K_IQ_BLOCK_S2DO_DIGITAL_EFFECT_X,
	SP5K_IQ_BLOCK_S2DO_DIGITAL_EFFECT_Y,
	SP5K_IQ_BLOCK_S2DO_PURPLE_FRING,

	SP5K_IQ_BLOCK_Y_MOE,
	SP5K_IQ_BLOCK_UV_MOE,

	SP5K_IQ_BLOCK_MAX,
} sp5kIqBlocklSelector_t;

#if (SP5K_IQ_BLOCK_MAX != IQ_BLOCK_MAX)
	#error	"IQ_BLOCK_MAX is too small"
#endif

#ifdef _TT
	#error "Macro Confliction: _TT has defined"
#endif

#define _TT(S) S /* for IQ CFG Testing */
typedef enum sp5kIqCfgSelector_e {
	/* dark sub */
	SP5K_IQ_CFG_DARK_SUB_HIGH_THR			_TT(= IQ_CFG_DARK_SUB_HIGH_THR),
	SP5K_IQ_CFG_DARK_SUB_LOW_THR,

	/* ob */
	SP5K_IQ_CFG_OB_MODE		                _TT(= IQ_CFG_OB_MODE),
	SP5K_IQ_CFG_OB_THR,
	SP5K_IQ_CFG_OB_VAL_SEL,
	SP5K_IQ_CFG_OB_WIN0_X_START,
	SP5K_IQ_CFG_OB_WIN0_Y_START,
	SP5K_IQ_CFG_OB_WIN0_X_END,
	SP5K_IQ_CFG_OB_WIN0_Y_END,
	SP5K_IQ_CFG_OB_WIN1_X_START,
	SP5K_IQ_CFG_OB_WIN1_Y_START,
	SP5K_IQ_CFG_OB_WIN1_X_END,
	SP5K_IQ_CFG_OB_WIN1_Y_END,
	SP5K_IQ_CFG_OB_MANUAL_VAL,
	SP5K_IQ_CFG_OB_AUTO_R,
	SP5K_IQ_CFG_OB_AUTO_GR,
	SP5K_IQ_CFG_OB_AUTO_B,
	SP5K_IQ_CFG_OB_AUTO_GB,
	SP5K_IQ_CFG_OB_AUTO_DET_ONLY,
	SP5K_IQ_CFG_OB_MAX,

	/* wb offset */
	SP5K_IQ_CFG_WB_OFS_R					_TT(= IQ_CFG_WB_OFS_R),
	SP5K_IQ_CFG_WB_OFS_GR,
	SP5K_IQ_CFG_WB_OFS_B,
	SP5K_IQ_CFG_WB_OFS_GB,
	SP5K_IQ_CFG_WB_OFS_ARRAY                _TT(= IQ_CFG_WB_OFS_ARRAY),

	/* bp fix */
	SP5K_IQ_CFG_BPFIX_R_THR					_TT(= IQ_CFG_BPFIX_R_THR),
	SP5K_IQ_CFG_BPFIX_G_THR,
	SP5K_IQ_CFG_BPFIX_B_THR,

	/*binning correction*/
	SP5K_IQ_CFG_BINNING_COR_POS             _TT(= IQ_CFG_BINNING_COR_POS),
	SP5K_IQ_CFG_BINNING_COR_BICUBIC,
	SP5K_IQ_CFG_BINNING_COR_H_CROP,
	SP5K_IQ_CFG_BINNING_COR_V_CROP,
	SP5K_IQ_CFG_BINNING_COR_H_FACTOR0,
	SP5K_IQ_CFG_BINNING_COR_H_FACTOR1,
	SP5K_IQ_CFG_BINNING_COR_H_FACTOR2,
	SP5K_IQ_CFG_BINNING_COR_H_FACTOR3,
	SP5K_IQ_CFG_BINNING_COR_V_FACTOR0,
	SP5K_IQ_CFG_BINNING_COR_V_FACTOR1,
	SP5K_IQ_CFG_BC_MAX,

	/* wb pre gain */
	SP5K_IQ_CFG_WB_PRE_GAIN_R_GAIN          _TT(= IQ_CFG_WB_PRE_GAIN_R_GAIN),
	SP5K_IQ_CFG_WB_PRE_GAIN_GR_GAIN,
	SP5K_IQ_CFG_WB_PRE_GAIN_B_GAIN,
	SP5K_IQ_CFG_WB_PRE_GAIN_GB_GAIN,

	/* lsc */
	SP5K_IQ_CFG_LSC_GAIN                    _TT(= IQ_CFG_LSC_GAIN),
	SP5K_IQ_CFG_LSC_BASIC_CHANNEL,
	SP5K_IQ_CFG_LSC_ONE_LUT,
	SP5K_IQ_CFG_LSC_POS,
	SP5K_IQ_CFG_LSC_FIELD,

	/* internal */
	SP5K_IQ_CFG_LSC_CHANNEL_MODE_INTERNAL,
	SP5K_IQ_CFG_LSC_IS_PV_INTERNAL,
	SP5K_IQ_CFG_LSC_TBL_X_SIZE_INTERNAL,
	SP5K_IQ_CFG_LSC_TBL_Y_SIZE_INTERNAL,
	SP5K_IQ_CFG_LSC_IMG_X_SIZE_INTERNAL,
	SP5K_IQ_CFG_LSC_IMG_Y_SIZE_INTERNAL,
	SP5K_IQ_CFG_LSC_X_OFS_INTERNAL,
	SP5K_IQ_CFG_LSC_Y_OFS_INTERNAL,

	SP5K_IQ_CFG_LSC_MAX,

	/* ca */
	SP5K_IQ_CFG_CA_R_X_GAIN                 _TT(= IQ_CFG_CA_R_X_GAIN),
	SP5K_IQ_CFG_CA_R_Y_GAIN,
	SP5K_IQ_CFG_CA_B_X_GAIN,
	SP5K_IQ_CFG_CA_B_Y_GAIN,

	SP5K_IQ_CFG_CA_MODE_INTERNAL,
	SP5K_IQ_CFG_CA_STEP_INTERNAL,
	SP5K_IQ_CFG_CA_X_OFFSET_INTERNAL,
	SP5K_IQ_CFG_CA_Y_OFFSET_INTERNAL,
	SP5K_IQ_CFG_CA_X_SIZE_INTERNAL,
	SP5K_IQ_CFG_CA_Y_SIZE_INTERNAL,

	SP5K_IQ_CFG_CA_MAX,

	/* ard */
	SP5K_IQ_CFG_ARD_BLUR_MASK_G             _TT(= IQ_CFG_ARD_BLUR_MASK_G),
	SP5K_IQ_CFG_ARD_BLUR_MASK_RB,

	SP5K_IQ_CFG_ARD_VAR_FAC,
	SP5K_IQ_CFG_ARD_RAC_BIT,
	SP5K_IQ_CFG_ARD_MULTI_THR_EN,

	SP5K_IQ_CFG_ARD_SPK_OPT2_G,
	SP5K_IQ_CFG_ARD_SPK_OPT2_RB,

	SP5K_IQ_CFG_ARD_VAR_SCALE_R,
	SP5K_IQ_CFG_ARD_VAR_SCALE_G,
	SP5K_IQ_CFG_ARD_VAR_SCALE_B,

	SP5K_IQ_CFG_ARD_LOW_THR_R,
	SP5K_IQ_CFG_ARD_LOW_THR_G,
	SP5K_IQ_CFG_ARD_LOW_THR_B,

	SP5K_IQ_CFG_ARD_HIGH_THR_R0,
	SP5K_IQ_CFG_ARD_HIGH_THR_G0,
	SP5K_IQ_CFG_ARD_HIGH_THR_B0,

	SP5K_IQ_CFG_ARD_CONTRAST_GAIN_R,
	SP5K_IQ_CFG_ARD_CONTRAST_GAIN_G,
	SP5K_IQ_CFG_ARD_CONTRAST_GAIN_B,

	SP5K_IQ_CFG_ARD_DEGRID_NOISE_EN,

	SP5K_IQ_CFG_ARD_DN_Y_THR_CTR,
	SP5K_IQ_CFG_ARD_DN_Y_NEG_THR,
	SP5K_IQ_CFG_ARD_DN_Y_POS_THR,


	SP5K_IQ_CFG_ARD_DN_UV_THR_CTR,
	SP5K_IQ_CFG_ARD_DN_UV_POS_THR,
	SP5K_IQ_CFG_ARD_DN_UV_NEG_THR,

	SP5K_IQ_CFG_ARD_DIV_FAC,
	SP5K_IQ_CFG_ARD_CDP_EN,
	SP5K_IQ_CFG_ARD_CDP_R_SEL,
	SP5K_IQ_CFG_ARD_CDP_G_SEL,
	SP5K_IQ_CFG_ARD_CDP_B_SEL,

	SP5K_IQ_CFG_ARD_MAX,

	/* ARD cornor denoise*/
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_RATIO_EN  _TT(= IQ_CFG_ARD_CORNER_DENOISE_RATIO_EN),
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_RATIO,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_IDX_OFS,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_STEP1,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_STEP2,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_CX,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_CY,

	SP5K_IQ_CFG_ARD_CORNER_DENOISE_DEG1,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_DEG2,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_DEG3,
	SP5K_IQ_CFG_ARD_CORNER_DENOISE_DEG4,

	SP5K_IQ_CFG_ARD_CORNER_DENOISE_MAX,

	/* depeak */
	SP5K_IQ_CFG_DEPEAK_HF_MODE            _TT(= IQ_CFG_DEPEAK_HF_MODE),
	SP5K_IQ_CFG_DEPEAK_R_POS_THR,
	SP5K_IQ_CFG_DEPEAK_R_NEG_THR,
	SP5K_IQ_CFG_DEPEAK_R_PIXEL_CNT,

	SP5K_IQ_CFG_DEPEAK_G_POS_THR,
	SP5K_IQ_CFG_DEPEAK_G_NEG_THR,
	SP5K_IQ_CFG_DEPEAK_G_PIXEL_CNT,

	SP5K_IQ_CFG_DEPEAK_B_POS_THR,
	SP5K_IQ_CFG_DEPEAK_B_NEG_THR,
	SP5K_IQ_CFG_DEPEAK_B_PIXEL_CNT,

	SP5K_IQ_CFG_DEPEAK_R_BAD_THR,
	SP5K_IQ_CFG_DEPEAK_R_SHRINK_THR,
	SP5K_IQ_CFG_DEPEAK_R_CLOSE_THR,
	SP5K_IQ_CFG_DEPEAK_R_SLOPE,

	SP5K_IQ_CFG_DEPEAK_G_BAD_THR,
	SP5K_IQ_CFG_DEPEAK_G_SHRINK_THR,
	SP5K_IQ_CFG_DEPEAK_G_CLOSE_THR,
	SP5K_IQ_CFG_DEPEAK_G_SLOPE,

	SP5K_IQ_CFG_DEPEAK_B_BAD_THR,
	SP5K_IQ_CFG_DEPEAK_B_SHRINK_THR,
	SP5K_IQ_CFG_DEPEAK_B_CLOSE_THR,
	SP5K_IQ_CFG_DEPEAK_B_SLOPE,

	SP5K_IQ_CFG_DEPEAK_MAX,

	/* wb gain */
	SP5K_IQ_CFG_WB_GAIN_R_GAIN              _TT(= IQ_CFG_WB_GAIN_R_GAIN),
	SP5K_IQ_CFG_WB_GAIN_GR_GAIN,
	SP5K_IQ_CFG_WB_GAIN_B_GAIN,
	SP5K_IQ_CFG_WB_GAIN_GB_GAIN,

	SP5K_IQ_CFG_WB_GAIN_R_OFS,
	SP5K_IQ_CFG_WB_GAIN_GR_OFS,
	SP5K_IQ_CFG_WB_GAIN_B_OFS,
	SP5K_IQ_CFG_WB_GAIN_GB_OFS,

	SP5K_IQ_CFG_WB_GAIN_GLOBAL_GAIN        _TT(= IQ_CFG_WB_GAIN_GLOBAL_GAIN),
	SP5K_IQ_CFG_WB_GAIN_R_SEN,
	SP5K_IQ_CFG_WB_GAIN_GR_SEN,
	SP5K_IQ_CFG_WB_GAIN_B_SEN,
	SP5K_IQ_CFG_WB_GAIN_GB_SEN,

	SP5K_IQ_CFG_WB_GAIN_MAX,

	/* wb gain 2*/
	SP5K_IQ_CFG_WB_GAIN2_R_GAIN            _TT(= IQ_CFG_WB_GAIN2_R_GAIN),
	SP5K_IQ_CFG_WB_GAIN2_GR_GAIN,
	SP5K_IQ_CFG_WB_GAIN2_B_GAIN,
	SP5K_IQ_CFG_WB_GAIN2_GB_GAIN,


	/* interpolation */
	SP5K_IQ_CFG_INTPL_HDIV_LOW             _TT(= IQ_CFG_INTPL_HDIV_LOW),
	SP5K_IQ_CFG_INTPL_VDIV_LOW,
	SP5K_IQ_CFG_INTPL_HDIV_HIGH,
	SP5K_IQ_CFG_INTPL_VDIV_HIGH,
	SP5K_IQ_CFG_INTPL_THR1,
	SP5K_IQ_CFG_INTPL_THR3,
	SP5K_IQ_CFG_INTPL_THR2,
	SP5K_IQ_CFG_INTPL_THR4,
	SP5K_IQ_CFG_INTPL_CLIP_OPT,
	SP5K_IQ_CFG_INTPL_CLIP_EN,

	SP5K_IQ_CFG_INTPL_MAX_DIF_RATIO,
	SP5K_IQ_CFG_INTPL_MIN_DIF_RATIO,

	SP5K_IQ_CFG_INTPL_GGESP_ARRAY          _TT(= IQ_CFG_INTPL_GGESP_ARRAY),
	SP5K_IQ_CFG_INTPL_RBESP_ARRAY          _TT(= IQ_CFG_INTPL_RBESP_ARRAY),

	SP5K_IQ_CFG_INTPL_MAX,

	/* rgb denoise */
	SP5K_IQ_CFG_RGB_DENOISE_WEIGHT         _TT(= IQ_CFG_RGB_DENOISE_WEIGHT),
	SP5K_IQ_CFG_RGB_DENOISE_TEST,
	SP5K_IQ_CFG_RGB_DENOISE_GMODE,
	SP5K_IQ_CFG_RGB_DENOISE_MIN_SELP,
	SP5K_IQ_CFG_RGB_DENOISE_MIN_SELN,

	/* white/dark clip */
	SP5K_IQ_CFG_CLIP1_DC_RG_THR            _TT(= IQ_CFG_CLIP1_DC_RG_THR),
	SP5K_IQ_CFG_CLIP1_DC_BG_THR,

	SP5K_IQ_CFG_CLIP1_WHITE_CH,
	SP5K_IQ_CFG_CLIP1_WHITE_X_LVL,
	SP5K_IQ_CFG_CLIP1_WHITE_Y_LVL,

	SP5K_IQ_CFG_CLIP1_WHITE_X_THR,
	SP5K_IQ_CFG_CLIP1_WHITE_Y_THR,

	SP5K_IQ_CFG_CLIP1_DARK_CH,
	SP5K_IQ_CFG_CLIP1_DARK_X_LVL,
	SP5K_IQ_CFG_CLIP1_DARK_Y_LVL,

	SP5K_IQ_CFG_CLIP1_DARK_X_THR,
	SP5K_IQ_CFG_CLIP1_DARK_Y_THR,

	SP5K_IQ_CFG_CLIP2_WHITE_CH,
	SP5K_IQ_CFG_CLIP2_WHITE_X_LVL,
	SP5K_IQ_CFG_CLIP2_WHITE_Y_LVL,

	SP5K_IQ_CFG_CLIP2_WHITE_X_THR,
	SP5K_IQ_CFG_CLIP2_WHITE_Y_THR,

	SP5K_IQ_CFG_CLIP2_DARK_CH,
	SP5K_IQ_CFG_CLIP2_DARK_X_LVL,
	SP5K_IQ_CFG_CLIP2_DARK_Y_LVL,

	SP5K_IQ_CFG_CLIP2_DARK_X_THR,
	SP5K_IQ_CFG_CLIP2_DARK_Y_THR,

	SP5K_IQ_CFG_CLIP2_DC_RG_THR,
	SP5K_IQ_CFG_CLIP2_DC_BG_THR,

	SP5K_IQ_CFG_CLIP_MAX,

	/* color matrix */
	SP5K_IQ_CFG_CM_ARRAY                  _TT(= IQ_CFG_CM_ARRAY),
	SP5K_IQ_CFG_CM_R_OFFSET               _TT(= IQ_CFG_CM_R_OFFSET),
	SP5K_IQ_CFG_CM_G_OFFSET,
	SP5K_IQ_CFG_CM_B_OFFSET,

	/* rgb gamma */
	SP5K_IQ_CFG_RGB_GAMMA_FLOW            _TT(= IQ_CFG_RGB_GAMMA_FLOW),
	SP5K_IQ_CFG_RGB_GAMMA_INVERSE,
	SP5K_IQ_CFG_RGB_GAMMA_ROFFSET,
	SP5K_IQ_CFG_RGB_GAMMA_GOFFSET,
	SP5K_IQ_CFG_RGB_GAMMA_BOFFSET,

     /*3D lut*/
	SP5K_IQ_CFG_3D_LUT_R_OFS              _TT(= IQ_CFG_3D_LUT_R_OFS),
	SP5K_IQ_CFG_3D_LUT_G_OFS,
	SP5K_IQ_CFG_3D_LUT_B_OFS,

	/* color matrix 2 */
	SP5K_IQ_CFG_CM2_ARRAY                 _TT(= IQ_CFG_CM2_ARRAY),
	SP5K_IQ_CFG_CM2_R_OFFSET              _TT(= IQ_CFG_CM2_R_OFFSET),
	SP5K_IQ_CFG_CM2_G_OFFSET,
	SP5K_IQ_CFG_CM2_B_OFFSET,

	/* hue correction */
	SP5K_IQ_CFG_HUE_CLAMP_U               _TT(= IQ_CFG_HUE_CLAMP_U),
	SP5K_IQ_CFG_HUE_CLAMP_V,

	SP5K_IQ_CFG_HUE_LOW_THR,
	SP5K_IQ_CFG_HUE_WIN_WEIGHT,

	/*Y Gamma*/
	SP5K_IQ_CFG_Y_GAMMA_OFS               _TT(= IQ_CFG_Y_GAMMA_OFS),
	SP5K_IQ_CFG_Y_GAMMA_INVERSE_EN,

	/* wdr */
	SP5K_IQ_CFG_WDR_MODE                  _TT(= IQ_CFG_WDR_MODE),
	SP5K_IQ_CFG_WDR_Q_SCALE_FACTOR,
	SP5K_IQ_CFG_WDR_Q_ENHANCE_SCALE_FACTOR,

	SP5K_IQ_CFG_WDR_CONTRAST_GAIN,
	SP5K_IQ_CFG_WDR_CONTRAST_OFS,

	SP5K_IQ_CFG_WDR_Q_LUT_ARRAY           _TT(= IQ_CFG_WDR_Q_LUT_ARRAY),
	SP5K_IQ_CFG_WDR_U_THR_LUT_ARRAY       _TT(= IQ_CFG_WDR_U_THR_LUT_ARRAY),
	SP5K_IQ_CFG_WDR_V_THR_LUT_ARRAY       _TT(= IQ_CFG_WDR_V_THR_LUT_ARRAY),

	SP5K_IQ_CFG_WDR_MAX,

	/* aa */
	SP5K_IQ_CFG_AA_MODE                   _TT(= IQ_CFG_AA_MODE),
	SP5K_IQ_CFG_AA_UV_MODE,
	SP5K_IQ_CFG_AA_CLAMP_U,
	SP5K_IQ_CFG_AA_CLAMP_V,

	SP5K_IQ_CFG_AA_THR,
	SP5K_IQ_CFG_AA_X_SUB,
	SP5K_IQ_CFG_AA_Y_SUB,

	SP5K_IQ_CFG_AA_SHRINK_MODE,
	SP5K_IQ_CFG_AA_SHRINK_SCALE,

	SP5K_IQ_CFG_AA_STRNGTH_LEVEL,
	SP5K_IQ_CFG_AA_STRNGTH_WEIGHT,

	SP5K_IQ_CFG_AA_MAX,

	/* ahd */
	SP5K_IQ_CFG_AHD_SCL_DOWN_ROUND_MODE  _TT(= IQ_CFG_AHD_SCL_DOWN_ROUND_MODE),
	SP5K_IQ_CFG_AHD_SCL_UP_ROUND_MODE,

	SP5K_IQ_CFG_AHD_UV_RATIO,

	SP5K_IQ_CFG_AHD_Y0_IIR_EN,
	SP5K_IQ_CFG_AHD_Y1_IIR_EN,
	SP5K_IQ_CFG_AHD_Y2_IIR_EN,
	SP5K_IQ_CFG_AHD_Y3_IIR_EN,

	SP5K_IQ_CFG_AHD_UV0_IIR_EN,
	SP5K_IQ_CFG_AHD_UV1_IIR_EN,
	SP5K_IQ_CFG_AHD_UV2_IIR_EN,
	SP5K_IQ_CFG_AHD_UV3_IIR_EN,

	SP5K_IQ_CFG_AHD_Y0_LEVEL_EN,
	SP5K_IQ_CFG_AHD_Y1_LEVEL_EN,
	SP5K_IQ_CFG_AHD_Y2_LEVEL_EN,
	SP5K_IQ_CFG_AHD_Y3_LEVEL_EN,

	SP5K_IQ_CFG_AHD_UV0_LEVEL_EN,
	SP5K_IQ_CFG_AHD_UV1_LEVEL_EN,
	SP5K_IQ_CFG_AHD_UV2_LEVEL_EN,
	SP5K_IQ_CFG_AHD_UV3_LEVEL_EN,

	SP5K_IQ_CFG_AHD_DENOISE_MODE,
	SP5K_IQ_CFG_AHD_UV_AVERAGE_EN,

	SP5K_IQ_CFG_AHD_Y0_HF_MODE0,
	SP5K_IQ_CFG_AHD_Y0_HF_MODE1,
	SP5K_IQ_CFG_AHD_Y1_HF_MODE0,
	SP5K_IQ_CFG_AHD_Y1_HF_MODE1,
	SP5K_IQ_CFG_AHD_Y2_HF_MODE0,
	SP5K_IQ_CFG_AHD_Y2_HF_MODE1,
	SP5K_IQ_CFG_AHD_Y3_HF_MODE0,
	SP5K_IQ_CFG_AHD_Y3_HF_MODE1,

	SP5K_IQ_CFG_AHD_UV0_HF_MODE,
	SP5K_IQ_CFG_AHD_UV1_HF_MODE,
	SP5K_IQ_CFG_AHD_UV2_HF_MODE,
	SP5K_IQ_CFG_AHD_UV3_HF_MODE,

	SP5K_IQ_CFG_AHD_Y2_BLUR_MASK_OPT,
	SP5K_IQ_CFG_AHD_Y3_BLUR_MASK_OPT,
	SP5K_IQ_CFG_AHD_UV2_BLUR_MASK_OPT,
	SP5K_IQ_CFG_AHD_UV3_BLUR_MASK_OPT,


	SP5K_IQ_CFG_AHD_Y0_SCL,
	SP5K_IQ_CFG_AHD_Y1_SCL,
	SP5K_IQ_CFG_AHD_Y2_SCL,
	SP5K_IQ_CFG_AHD_Y3_SCL,

	SP5K_IQ_CFG_AHD_U0_SCL,
	SP5K_IQ_CFG_AHD_U1_SCL,
	SP5K_IQ_CFG_AHD_U2_SCL,
	SP5K_IQ_CFG_AHD_U3_SCL,

	SP5K_IQ_CFG_AHD_V0_SCL,
	SP5K_IQ_CFG_AHD_V1_SCL,
	SP5K_IQ_CFG_AHD_V2_SCL,
	SP5K_IQ_CFG_AHD_V3_SCL,

	SP5K_IQ_CFG_AHD_Y0_CONST_GAIN,
	SP5K_IQ_CFG_AHD_Y1_CONST_GAIN,
	SP5K_IQ_CFG_AHD_Y2_CONST_GAIN,
	SP5K_IQ_CFG_AHD_Y3_CONST_GAIN,

	SP5K_IQ_CFG_AHD_U0_CONST_GAIN,
	SP5K_IQ_CFG_AHD_U1_CONST_GAIN,
	SP5K_IQ_CFG_AHD_U2_CONST_GAIN,
	SP5K_IQ_CFG_AHD_U3_CONST_GAIN,

	SP5K_IQ_CFG_AHD_V0_CONST_GAIN,
	SP5K_IQ_CFG_AHD_V1_CONST_GAIN,
	SP5K_IQ_CFG_AHD_V2_CONST_GAIN,
	SP5K_IQ_CFG_AHD_V3_CONST_GAIN,


	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_Y0_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_Y1_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_Y2_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_Y3_LOW_THR_POS_HF_THR2,


	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_UV0_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_UV1_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_UV2_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_AHD_UV3_LOW_THR_POS_HF_THR2,

    SP5K_IQ_CFG_AHD_Y0_HI_THR,
    SP5K_IQ_CFG_AHD_Y1_HI_THR,
    SP5K_IQ_CFG_AHD_Y2_HI_THR,
    SP5K_IQ_CFG_AHD_Y3_HI_THR,

    SP5K_IQ_CFG_AHD_UV0_HI_THR,
    SP5K_IQ_CFG_AHD_UV1_HI_THR,
    SP5K_IQ_CFG_AHD_UV2_HI_THR,
    SP5K_IQ_CFG_AHD_UV3_HI_THR,

	SP5K_IQ_CFG_AHD_SPK_OPT2_Y0,
	SP5K_IQ_CFG_AHD_SPK_OPT3_Y0,
	SP5K_IQ_CFG_AHD_SPK_OPT2_Y1,
	SP5K_IQ_CFG_AHD_SPK_OPT3_Y1,

	SP5K_IQ_CFG_AHD_SPK_OPT2_Y2,
	SP5K_IQ_CFG_AHD_SPK_OPT3_Y2,
	SP5K_IQ_CFG_AHD_SPK_OPT2_Y3,
	SP5K_IQ_CFG_AHD_SPK_OPT3_Y3,

	SP5K_IQ_CFG_AHD_SPK_OPT2_UV0,
	SP5K_IQ_CFG_AHD_SPK_OPT3_UV0,
	SP5K_IQ_CFG_AHD_SPK_OPT2_UV1,
	SP5K_IQ_CFG_AHD_SPK_OPT3_UV1,

	SP5K_IQ_CFG_AHD_SPK_OPT2_UV2,
	SP5K_IQ_CFG_AHD_SPK_OPT3_UV2,
	SP5K_IQ_CFG_AHD_SPK_OPT2_UV3,
	SP5K_IQ_CFG_AHD_SPK_OPT3_UV3,


	SP5K_IQ_CFG_AHD_SPK_VAR_Y_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_U_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_V_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_U2_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_V2_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_U3_GAIN,
	SP5K_IQ_CFG_AHD_SPK_VAR_V3_GAIN,

	SP5K_IQ_CFG_AHD_SHR_Y0_GAIN,
	SP5K_IQ_CFG_AHD_SHR_Y1_GAIN,
	SP5K_IQ_CFG_AHD_SHR_Y2_GAIN,
	SP5K_IQ_CFG_AHD_SHR_Y3_GAIN,

	SP5K_IQ_CFG_AHD_SHR_UV0_GAIN,
	SP5K_IQ_CFG_AHD_SHR_UV1_GAIN,
	SP5K_IQ_CFG_AHD_SHR_UV2_GAIN,
	SP5K_IQ_CFG_AHD_SHR_UV3_GAIN,

	SP5K_IQ_CFG_AHD_Y0_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_Y1_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_Y2_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_Y3_SCL_FACTOR,

	SP5K_IQ_CFG_AHD_UV0_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_UV1_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_UV2_SCL_FACTOR,
	SP5K_IQ_CFG_AHD_UV3_SCL_FACTOR,


	SP5K_IQ_CFG_AHD_Y_HF_VAR_GAIN,
	SP5K_IQ_CFG_AHD_U_HF_VAR_GAIN,
	SP5K_IQ_CFG_AHD_V_HF_VAR_GAIN,

	SP5K_IQ_CFG_AHD_Y0_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_Y0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_Y1_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_Y1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_Y2_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_Y2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_Y3_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_Y3_VAR_TBL_ARRAY),

	SP5K_IQ_CFG_AHD_U0_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_U0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_U1_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_U1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_U2_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_U2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_U3_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_U3_VAR_TBL_ARRAY),

	SP5K_IQ_CFG_AHD_V0_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_V0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_V1_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_V1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_V2_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_V2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_AHD_V3_VAR_TBL_ARRAY    _TT(= IQ_CFG_AHD_V3_VAR_TBL_ARRAY),

    SP5K_IQ_CFG_AHD_DOT_EDGE_DIV        _TT(= IQ_CFG_AHD_DOT_EDGE_DIV),
	SP5K_IQ_CFG_AHD_DOT_EDGE_MODE,
	SP5K_IQ_CFG_AHD_DOT_EDGE_SHR,


	SP5K_IQ_CFG_AHD_DOT_EDGE_SHR_THR,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT0,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT1,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT2,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT3,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT4,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT5,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT6,
	SP5K_IQ_CFG_AHD_DOT_EDGE_LUT7,

	SP5K_IQ_CFG_AHD_DOT_EDGE_WIDTH,
	SP5K_IQ_CFG_AHD_DOT_EDGE_THR,
	SP5K_IQ_CFG_AHD_DOT_MAX_NEG_AMP,
	SP5K_IQ_CFG_AHD_DOT_MAX_POS_AMP,
	SP5K_IQ_CFG_AHD_DOT_HF_MAX_NEG_AMP,
	SP5K_IQ_CFG_AHD_DOT_HF_MAX_POS_AMP,

	SP5K_IQ_CFG_AHD_GRAY_Y_OPT,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT0,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT1,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT2,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT3,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT4,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT5,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT6,
	SP5K_IQ_CFG_AHD_DOT_NOISE_SHR_LUT7,


	SP5K_IQ_CFG_AHD_GRAY_Y_LUT0,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT1,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT2,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT3,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT4,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT5,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT6,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT7,
	SP5K_IQ_CFG_AHD_GRAY_Y_LUT8,


	SP5K_IQ_CFG_AHD_GRAY_LEVEL0,
	SP5K_IQ_CFG_AHD_GRAY_LEVEL1,
	SP5K_IQ_CFG_AHD_GRAY_LEVEL2,
	SP5K_IQ_CFG_AHD_GRAY_LEVEL3,

	SP5K_IQ_CFG_AHD_COR_EN_LEVEL0,
	SP5K_IQ_CFG_AHD_COR_EN_LEVEL1,
	SP5K_IQ_CFG_AHD_COR_EN_LEVEL2,
	SP5K_IQ_CFG_AHD_COR_EN_LEVEL3,

	SP5K_IQ_CFG_AHD_GRAY_EN_LEVEL0,
	SP5K_IQ_CFG_AHD_GRAY_EN_LEVEL1,
	SP5K_IQ_CFG_AHD_GRAY_EN_LEVEL2,
	SP5K_IQ_CFG_AHD_GRAY_EN_LEVEL3,

	SP5K_IQ_CFG_AHD_COR_MIN_THR_U0,
	SP5K_IQ_CFG_AHD_COR_MIN_THR_U2,
	SP5K_IQ_CFG_AHD_COR_MIN_THR_V0,
	SP5K_IQ_CFG_AHD_COR_MIN_THR_V2,

	SP5K_IQ_CFG_AHD_COR_THR3_U0,
	SP5K_IQ_CFG_AHD_COR_THR3_U2,
	SP5K_IQ_CFG_AHD_COR_THR3_V0,
	SP5K_IQ_CFG_AHD_COR_THR3_V2,

	SP5K_IQ_CFG_AHD_COR_THR2_U0,
	SP5K_IQ_CFG_AHD_COR_THR2_U2,
	SP5K_IQ_CFG_AHD_COR_THR2_V0,
	SP5K_IQ_CFG_AHD_COR_THR2_V2,

	SP5K_IQ_CFG_AHD_COR_THR1_U0,
	SP5K_IQ_CFG_AHD_COR_THR1_U2,
	SP5K_IQ_CFG_AHD_COR_THR1_V0,
	SP5K_IQ_CFG_AHD_COR_THR1_V2,

	SP5K_IQ_CFG_AHD_COR_VAL3_U0,
	SP5K_IQ_CFG_AHD_COR_VAL3_U2,
	SP5K_IQ_CFG_AHD_COR_VAL3_V0,
	SP5K_IQ_CFG_AHD_COR_VAL3_V2,

	SP5K_IQ_CFG_AHD_COR_VAL2_U0,
	SP5K_IQ_CFG_AHD_COR_VAL2_U2,
	SP5K_IQ_CFG_AHD_COR_VAL2_V0,
	SP5K_IQ_CFG_AHD_COR_VAL2_V2,

	SP5K_IQ_CFG_AHD_COR_VAL1_U0,
	SP5K_IQ_CFG_AHD_COR_VAL1_U2,
	SP5K_IQ_CFG_AHD_COR_VAL1_V0,
	SP5K_IQ_CFG_AHD_COR_VAL1_V2,

	SP5K_IQ_CFG_AHD_GRAY_MIN_THR,
	SP5K_IQ_CFG_AHD_GRAY_MIN_U0,
	SP5K_IQ_CFG_AHD_GRAY_MIN_U1,
	SP5K_IQ_CFG_AHD_GRAY_MIN_U2,
	SP5K_IQ_CFG_AHD_GRAY_MIN_U3,

	SP5K_IQ_CFG_AHD_GRAY_MIN_V0,
	SP5K_IQ_CFG_AHD_GRAY_MIN_V1,
	SP5K_IQ_CFG_AHD_GRAY_MIN_V2,
	SP5K_IQ_CFG_AHD_GRAY_MIN_V3,

	SP5K_IQ_CFG_AHD_Y_OFS,
	SP5K_IQ_CFG_AHD_U_OFS,
	SP5K_IQ_CFG_AHD_V_OFS,

	SP5K_IQ_CFG_AHD_SPK_VAR_Y_GAIN_0,
	SP5K_IQ_CFG_AHD_SPK_VAR_Y_GAIN_3,

	SP5K_IQ_CFG_AHD_MAX,

	/* AHD Y cornor denoise*/
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_RATIO_EN   _TT(= IQ_CFG_AHD_Y_CORNER_DENOISE_RATIO_EN),
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_RATIO,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_IDX_OFS,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_STEP1,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_STEP2,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_CX,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_CY,

	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_DEG1,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_DEG2,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_DEG3,
	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_DEG4,

	SP5K_IQ_CFG_AHD_Y_CORNER_DENOISE_MAX,

	/* AHD UV cornor denoise*/
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_RATIO_EN  _TT(= IQ_CFG_AHD_UV_CORNER_DENOISE_RATIO_EN),
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_RATIO,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_IDX_OFS,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_STEP1,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_STEP2,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_CX,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_CY,

	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_DEG1,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_DEG2,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_DEG3,
	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_DEG4,

	SP5K_IQ_CFG_AHD_UV_CORNER_DENOISE_MAX,

	/* yef/ynf */
	SP5K_IQ_CFG_YEF_FILTER                      _TT(= IQ_CFG_YEF_FILTER),
	SP5K_IQ_CFG_YEF_EDGE_PATTERN,
	SP5K_IQ_CFG_YEF_YNF_THR,
	SP5K_IQ_CFG_YEF_YNF_EDGE_DIV,
	SP5K_IQ_CFG_YNF_EDGE_SHR_THR,
	SP5K_IQ_CFG_YEF5_FILT_OPT,
	SP5K_IQ_CFG_YEF3_FILT_OPT,
	SP5K_IQ_CFG_YEF_YNF_VAR_SCL_FACTOR,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SCL_FACTOR,
	SP5K_IQ_CFG_YEF_YNF_Y_EDGE_TRANS_W,
	SP5K_IQ_CFG_YNF_FILT_OPT,
	SP5K_IQ_CFG_YEF5_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_YEF3_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_YEF_EDGE_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_YEF_YNF_DIR_STRENGTH_LEVEL,
	SP5K_IQ_CFG_YEF_YNF_WT_STRENGTH_LEVEL,
	SP5K_IQ_CFG_YEF_YNF_STRONG_EDGE_LOW_THR,
	SP5K_IQ_CFG_YEF_YNF_OUT_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_YEF_YNF_WEAK_EDGE_LOW_THR,
	SP5K_IQ_CFG_YEF_YNF_WEAK_EDGE_VAR_THR,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL0,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL1,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL2,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL3,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL4,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL5,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL6,
	SP5K_IQ_CFG_YEF_YNF_EDGE_SHR_TBL7,

	SP5K_IQ_CFG_YEF_MAX,

	/* y edge */
	SP5K_IQ_CFG_Y_EDGE_SCALE                    _TT(= IQ_CFG_Y_EDGE_SCALE),
	SP5K_IQ_CFG_Y_EDGE_INDEX,
	SP5K_IQ_CFG_Y_EDGE_MAP_SCALE,

	SP5K_IQ_CFG_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_Y_EDGE_HIGH_THR,

	SP5K_IQ_CFG_Y_EDGE_YH_GAIN,
	SP5K_IQ_CFG_Y_EDGE_FINAL_LOW_THR,
	SP5K_IQ_CFG_Y_EDGE_FINAL_HIGH_THR,

	SP5K_IQ_CFG_Y_EDGE_FW_GAIN,

	SP5K_IQ_CFG_Y_EDGE_FILTER_ARRAY             _TT(= IQ_CFG_Y_EDGE_FILTER_ARRAY),
	SP5K_IQ_CFG_Y_EDGE_GAIN_ARRAY               _TT(= IQ_CFG_Y_EDGE_GAIN_ARRAY),

	SP5K_IQ_CFG_Y_EDGE_MAX,

	/* y corner edge */
	SP5K_IQ_CFG_Y_CORNER_EDGE_RATIO_SEL         _TT(= IQ_CFG_Y_CORNER_EDGE_RATIO_SEL),
	SP5K_IQ_CFG_Y_CORNER_EDGE_RATIO,
	SP5K_IQ_CFG_Y_CORNER_EDGE_IDX_OFFSET,
	SP5K_IQ_CFG_Y_CORNER_EDGE_STEP1,
	SP5K_IQ_CFG_Y_CORNER_EDGE_STEP2,
	SP5K_IQ_CFG_Y_CORNER_EDGE_CX,
	SP5K_IQ_CFG_Y_CORNER_EDGE_CY,
	SP5K_IQ_CFG_Y_CORNER_EDGE_EG1,
	SP5K_IQ_CFG_Y_CORNER_EDGE_EG2,
	SP5K_IQ_CFG_Y_CORNER_EDGE_EG3,
	SP5K_IQ_CFG_Y_CORNER_EDGE_EG4,
	SP5K_IQ_CFG_Y_CORNER_EDGE_P_FAC,
	SP5K_IQ_CFG_Y_CORNER_EDGE_N_FAC,
	SP5K_IQ_CFG_Y_CORNER_EDGE_MASK,

	SP5K_IQ_CFG_Y_CORNER_EDGE_MAX,

	/* uv core */
	SP5K_IQ_CFG_UV_CORE_U_MIN                   _TT(= IQ_CFG_UV_CORE_U_MIN),
	SP5K_IQ_CFG_UV_CORE_V_MIN,
	SP5K_IQ_CFG_UV_CORE_U_THR,
	SP5K_IQ_CFG_UV_CORE_V_THR,
	SP5K_IQ_CFG_UV_CORE_U_SHR,
	SP5K_IQ_CFG_UV_CORE_V_SHR,

	/* uv lpf */
	SP5K_IQ_CFG_UV_LPF_MODE                     _TT(= IQ_CFG_UV_LPF_MODE),
	SP5K_IQ_CFG_UV_LPF_RND_MODE,

	SP5K_IQ_CFG_UV_LPF_DIR_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_UV_LPF_AREA_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_UV_LPF_THR,
	SP5K_IQ_CFG_UV_LPF_DIR_MEDIAN_SEL,
	SP5K_IQ_CFG_UV_LPF_AREA_MEDIAN_SEL,

	SP5K_IQ_CFG_UV_LPF_SUP_EDGE_DIV,

	SP5K_IQ_CFG_UV_LPF_DIR_MODE,
	SP5K_IQ_CFG_UV_LPF_AREA_MODE,
	SP5K_IQ_CFG_UV_LPF_DIR_OPT,
	SP5K_IQ_CFG_UV_LPF_DIR_PAT_SEL,
	SP5K_IQ_CFG_UV_LPF_CNFY_MIN_SCL_FACT,
	SP5K_IQ_CFG_UV_LPF_Y_THR,
	SP5K_IQ_CFG_UV_LPF_Y_WIDTH,

	SP5K_IQ_CFG_UV_LPF_ARRAY                    _TT(= IQ_CFG_UV_LPF_ARRAY),

	SP5K_IQ_CFG_UV_LPF_MAX,

	/*YUV depeak*/
	SP5K_IQ_CFG_YUV_DEPEAK_OPT0                  _TT(= IQ_CFG_YUV_DEPEAK_OPT0),
	SP5K_IQ_CFG_YUV_DEPEAK_OPT1,
	SP5K_IQ_CFG_YUV_DEPEAK_MODE,

	/* digital effect */
	SP5K_IQ_CFG_DIGI_EFF_SOBEL_MASK_SEL         _TT(= IQ_CFG_DIGI_EFF_SOBEL_MASK_SEL),
	SP5K_IQ_CFG_DIGI_EFF_SOBEL_RIGHT_SHIFT,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_MODE_EN,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_MODE  ,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_RATIO  ,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_LIGHT  ,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_DEPTH  ,
	SP5K_IQ_CFG_DIGI_EFF_ECY1_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_ECY1_MODE  ,
	SP5K_IQ_CFG_DIGI_EFF_ECY2_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_ECU_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_ECV_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_ECY_SHIFT_BYTE ,
	SP5K_IQ_CFG_DIGI_EFF_ECUV_SHIFT_BYTE  ,

	SP5K_IQ_CFG_DIGI_EFF_Y_BRIGHT  ,
	SP5K_IQ_CFG_DIGI_EFF_U_BRIGHT  ,
	SP5K_IQ_CFG_DIGI_EFF_V_BRIGHT  ,

	SP5K_IQ_CFG_DIGI_EFF_Y_CONTRAST  ,
	SP5K_IQ_CFG_DIGI_EFF_U_CONTRAST  ,
	SP5K_IQ_CFG_DIGI_EFF_V_CONTRAST  ,

	SP5K_IQ_CFG_DIGI_EFF_Y_OFFSET  ,
	SP5K_IQ_CFG_DIGI_EFF_U_OFFSET  ,
	SP5K_IQ_CFG_DIGI_EFF_V_OFFSET  ,

	SP5K_IQ_CFG_DIGI_EFF_Y_LOW_THR  ,
	SP5K_IQ_CFG_DIGI_EFF_Y_HI_THR  ,

	SP5K_IQ_CFG_DIGI_EFF_DISTURB_VAL_SEL ,
	SP5K_IQ_CFG_DIGI_EFF_DISTURB_VAL_MODE ,

	SP5K_IQ_CFG_DIGI_EFF_NOR_Y_DISTURB  ,
	SP5K_IQ_CFG_DIGI_EFF_FACTOR1  ,
	SP5K_IQ_CFG_DIGI_EFF_FACTOR2  ,

	SP5K_IQ_CFG_DIGI_EFF_Y_LUT_EN ,
	SP5K_IQ_CFG_DIGI_EFF_UV_MATRIX_EN ,
	SP5K_IQ_CFG_DIGI_EFF_Y_LUT_SEL ,
	SP5K_IQ_CFG_DIGI_EFF_UV_MATRIX_ARRAY        _TT(= IQ_CFG_DIGI_EFF_UV_MATRIX_ARRAY),
	SP5K_IQ_CFG_DIGI_EFF_BI_EN                  _TT(= IQ_CFG_DIGI_EFF_BI_EN),
	SP5K_IQ_CFG_DIGI_EFF_BI_MODE_SEL ,
	SP5K_IQ_CFG_DIGI_EFF_BI_Y1_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_BI_Y2_SEL  ,
	SP5K_IQ_CFG_DIGI_EFF_BI_THR  ,

	SP5K_IQ_CFG_DIGI_EFF_MAX,

	/* purple fringing*/
	SP5K_IQ_CFG_PURPLE_FRINGE_SOBEL_MODE         _TT(= IQ_CFG_PURPLE_FRINGE_SOBEL_MODE),
	SP5K_IQ_CFG_PURPLE_FRINGE_BLUR_SIZE,
	SP5K_IQ_CFG_PURPLE_FRINGE_NORM_FACTOR,
	SP5K_IQ_CFG_PURPLE_FRINGE_NORM_SHIFT,
	SP5K_IQ_CFG_PURPLE_FRINGE_UV_EDGE0,
	SP5K_IQ_CFG_PURPLE_FRINGE_UV_EDGE1,

	SP5K_IQ_CFG_PURPLE_FRINGE_UV_EDGE_THR,
	SP5K_IQ_CFG_PURPLE_FRINGE_EPS_EXT_SIZE,
	SP5K_IQ_CFG_PURPLE_FRINGE_EPS_U_THR,
	SP5K_IQ_CFG_PURPLE_FRINGE_EPS_V_THR,

	SP5K_IQ_CFG_PURPLE_FRINGE_BLUR_THR,
	SP5K_IQ_CFG_PURPLE_FRINGE_BLUR_FACTOR,
	SP5K_IQ_CFG_PURPLE_FRINGE_BLUR_SHIFT,

	SP5K_IQ_CFG_PURPLE_FRINGE_MAX,

	/* temporal denoise */
	SP5K_IQ_CFG_TEMPORAL_DENOISE_MASK           _TT(= IQ_CFG_TEMPORAL_DENOISE_MASK),
	SP5K_IQ_CFG_TEMPORAL_DENOISE_LOW_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_HIGH_THR,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_MIN_WEIGHT,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_MAX_WEIGHT,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_WEIGHING,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_MIN_WEIGHT,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_MAX_WEIGHT,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_WEIGHING,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_DIFF_PARAM,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_N_DIFF_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_SB_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_DIFF_PARAM,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_DIFF_THR,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_EFILTER_EN,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_UV_EFILTER_EN,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_DEPEAK_NUM,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_Y_DEPEAK_THR,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_EF_Y_THR,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_EF_UV_THR,


	SP5K_IQ_CFG_TEMPORAL_DENOISE_GAIN,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_LEVEL,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_BASE_Y,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_BASE_UV,
	SP5K_IQ_CFG_TEMPORAL_DENOISE_GAP,

	SP5K_IQ_CFG_TEMPORAL_DENOISE_MAX,

	/* ldc */
	SP5K_IQ_CFG_LDC_GAIN                        _TT(= IQ_CFG_LDC_GAIN),

	/* Redo hue correction */
	SP5K_IQ_CFG_REDO_HUE_CLAMP_U               _TT(= IQ_CFG_REDO_HUE_CLAMP_U),
	SP5K_IQ_CFG_REDO_HUE_CLAMP_V,

	SP5K_IQ_CFG_REDO_HUE_LOW_THR,
	SP5K_IQ_CFG_REDO_HUE_WIN_WEIGHT,

	/*Y Gamma*/
	SP5K_IQ_CFG_REDO_Y_GAMMA_OFS               _TT(= IQ_CFG_REDO_Y_GAMMA_OFS),
	SP5K_IQ_CFG_REDO_Y_GAMMA_INVERSE_EN,

	/* wdr */
	SP5K_IQ_CFG_REDO_WDR_MODE                  _TT(= IQ_CFG_REDO_WDR_MODE),
	SP5K_IQ_CFG_REDO_WDR_Q_SCALE_FACTOR,
	SP5K_IQ_CFG_REDO_WDR_Q_ENHANCE_SCALE_FACTOR,

	SP5K_IQ_CFG_REDO_WDR_CONTRAST_GAIN,
	SP5K_IQ_CFG_REDO_WDR_CONTRAST_OFS,

	SP5K_IQ_CFG_REDO_WDR_Q_LUT_ARRAY           _TT(= IQ_CFG_REDO_WDR_Q_LUT_ARRAY),
	SP5K_IQ_CFG_REDO_WDR_U_THR_LUT_ARRAY       _TT(= IQ_CFG_REDO_WDR_U_THR_LUT_ARRAY),
	SP5K_IQ_CFG_REDO_WDR_V_THR_LUT_ARRAY       _TT(= IQ_CFG_REDO_WDR_V_THR_LUT_ARRAY),

	SP5K_IQ_CFG_REDO_WDR_MAX,

	/* aa */
	SP5K_IQ_CFG_REDO_AA_MODE                   _TT(= IQ_CFG_REDO_AA_MODE),
	SP5K_IQ_CFG_REDO_AA_UV_MODE,
	SP5K_IQ_CFG_REDO_AA_CLAMP_U,
	SP5K_IQ_CFG_REDO_AA_CLAMP_V,

	SP5K_IQ_CFG_REDO_AA_THR,
	SP5K_IQ_CFG_REDO_AA_X_SUB,
	SP5K_IQ_CFG_REDO_AA_Y_SUB,

	SP5K_IQ_CFG_REDO_AA_SHRINK_MODE,
	SP5K_IQ_CFG_REDO_AA_SHRINK_SCALE,

	SP5K_IQ_CFG_REDO_AA_STRNGTH_LEVEL,
	SP5K_IQ_CFG_REDO_AA_STRNGTH_WEIGHT,

	SP5K_IQ_CFG_REDO_AA_MAX,

	/* redo ahd */
	SP5K_IQ_CFG_REDO_AHD_SCL_DOWN_ROUND_MODE  _TT(= IQ_CFG_REDO_AHD_SCL_DOWN_ROUND_MODE),
	SP5K_IQ_CFG_REDO_AHD_SCL_UP_ROUND_MODE,

	SP5K_IQ_CFG_REDO_AHD_LEVEL4_EN,

	SP5K_IQ_CFG_REDO_AHD_UV_RATIO,

	SP5K_IQ_CFG_REDO_AHD_Y0_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_Y1_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_Y2_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_Y3_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_Y4_IIR_EN,

	SP5K_IQ_CFG_REDO_AHD_UV0_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_UV1_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_UV2_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_UV3_IIR_EN,
	SP5K_IQ_CFG_REDO_AHD_UV4_IIR_EN,

	SP5K_IQ_CFG_REDO_AHD_Y0_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_Y1_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_Y2_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_Y3_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_Y4_LEVEL_EN,

	SP5K_IQ_CFG_REDO_AHD_UV0_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_UV1_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_UV2_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_UV3_LEVEL_EN,
	SP5K_IQ_CFG_REDO_AHD_UV4_LEVEL_EN,

	SP5K_IQ_CFG_REDO_AHD_DENOISE_MODE,
	SP5K_IQ_CFG_REDO_AHD_UV_AVERAGE_EN,

	SP5K_IQ_CFG_REDO_AHD_Y0_HF_MODE0,
	SP5K_IQ_CFG_REDO_AHD_Y0_HF_MODE1,
	SP5K_IQ_CFG_REDO_AHD_Y1_HF_MODE0,
	SP5K_IQ_CFG_REDO_AHD_Y1_HF_MODE1,
	SP5K_IQ_CFG_REDO_AHD_Y2_HF_MODE0,
	SP5K_IQ_CFG_REDO_AHD_Y2_HF_MODE1,
	SP5K_IQ_CFG_REDO_AHD_Y3_HF_MODE0,
	SP5K_IQ_CFG_REDO_AHD_Y3_HF_MODE1,
	SP5K_IQ_CFG_REDO_AHD_Y4_HF_MODE0,
	SP5K_IQ_CFG_REDO_AHD_Y4_HF_MODE1,


	SP5K_IQ_CFG_REDO_AHD_UV0_HF_MODE,
	SP5K_IQ_CFG_REDO_AHD_UV1_HF_MODE,
	SP5K_IQ_CFG_REDO_AHD_UV2_HF_MODE,
	SP5K_IQ_CFG_REDO_AHD_UV3_HF_MODE,
	SP5K_IQ_CFG_REDO_AHD_UV4_HF_MODE,

	SP5K_IQ_CFG_REDO_AHD_Y2_BLUR_MASK_OPT,
	SP5K_IQ_CFG_REDO_AHD_Y3_BLUR_MASK_OPT,
	SP5K_IQ_CFG_REDO_AHD_Y4_BLUR_MASK_OPT,
	SP5K_IQ_CFG_REDO_AHD_UV2_BLUR_MASK_OPT,
	SP5K_IQ_CFG_REDO_AHD_UV3_BLUR_MASK_OPT,
	SP5K_IQ_CFG_REDO_AHD_UV4_BLUR_MASK_OPT,


	SP5K_IQ_CFG_REDO_AHD_Y0_SCL,
	SP5K_IQ_CFG_REDO_AHD_Y1_SCL,
	SP5K_IQ_CFG_REDO_AHD_Y2_SCL,
	SP5K_IQ_CFG_REDO_AHD_Y3_SCL,
	SP5K_IQ_CFG_REDO_AHD_Y4_SCL,

	SP5K_IQ_CFG_REDO_AHD_U0_SCL,
	SP5K_IQ_CFG_REDO_AHD_U1_SCL,
	SP5K_IQ_CFG_REDO_AHD_U2_SCL,
	SP5K_IQ_CFG_REDO_AHD_U3_SCL,
	SP5K_IQ_CFG_REDO_AHD_U4_SCL,

	SP5K_IQ_CFG_REDO_AHD_V0_SCL,
	SP5K_IQ_CFG_REDO_AHD_V1_SCL,
	SP5K_IQ_CFG_REDO_AHD_V2_SCL,
	SP5K_IQ_CFG_REDO_AHD_V3_SCL,
	SP5K_IQ_CFG_REDO_AHD_V4_SCL,

	SP5K_IQ_CFG_REDO_AHD_Y0_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_Y1_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_Y2_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_Y3_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_Y4_CONST_GAIN,

	SP5K_IQ_CFG_REDO_AHD_U0_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_U1_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_U2_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_U3_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_U4_CONST_GAIN,

	SP5K_IQ_CFG_REDO_AHD_V0_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_V1_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_V2_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_V3_CONST_GAIN,
	SP5K_IQ_CFG_REDO_AHD_V4_CONST_GAIN,


	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_PARAM0,


	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y0_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y1_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y2_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y3_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_Y4_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV0_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV1_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV2_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV3_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_REDO_AHD_UV4_LOW_THR_POS_HF_THR2,

    SP5K_IQ_CFG_REDO_AHD_Y0_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_Y1_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_Y2_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_Y3_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_Y4_HI_THR,

    SP5K_IQ_CFG_REDO_AHD_UV0_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_UV1_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_UV2_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_UV3_HI_THR,
    SP5K_IQ_CFG_REDO_AHD_UV4_HI_THR,

	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_Y0,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_Y0,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_Y1,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_Y1,

	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_Y2,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_Y2,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_Y3,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_Y3,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_Y4,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_Y4,


	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_UV0,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_UV0,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_UV1,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_UV1,

	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_UV2,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_UV2,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_UV3,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_UV3,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT2_UV4,
	SP5K_IQ_CFG_REDO_AHD_SPK_OPT3_UV4,


	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_Y_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_U_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_V_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_U2_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_V2_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_U3_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_V3_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_U4_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_V4_GAIN,

	SP5K_IQ_CFG_REDO_AHD_SHR_Y0_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_Y1_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_Y2_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_Y3_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_Y4_GAIN,

	SP5K_IQ_CFG_REDO_AHD_SHR_UV0_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_UV1_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_UV2_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_UV3_GAIN,
	SP5K_IQ_CFG_REDO_AHD_SHR_UV4_GAIN,

	SP5K_IQ_CFG_REDO_AHD_Y0_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_Y1_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_Y2_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_Y3_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_Y4_SCL_FACTOR,

	SP5K_IQ_CFG_REDO_AHD_UV0_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_UV1_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_UV2_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_UV3_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_AHD_UV4_SCL_FACTOR,

	SP5K_IQ_CFG_REDO_AHD_Y_HF_VAR_GAIN,
	SP5K_IQ_CFG_REDO_AHD_U_HF_VAR_GAIN,
	SP5K_IQ_CFG_REDO_AHD_V_HF_VAR_GAIN,

	SP5K_IQ_CFG_REDO_AHD_Y0_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_Y0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_Y1_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_Y1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_Y2_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_Y2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_Y3_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_Y3_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_Y4_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_Y4_VAR_TBL_ARRAY),

	SP5K_IQ_CFG_REDO_AHD_U0_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_U0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_U1_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_U1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_U2_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_U2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_U3_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_U3_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_U4_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_U4_VAR_TBL_ARRAY),

	SP5K_IQ_CFG_REDO_AHD_V0_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_V0_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_V1_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_V1_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_V2_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_V2_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_V3_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_V3_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_REDO_AHD_V4_VAR_TBL_ARRAY    _TT(= IQ_CFG_REDO_AHD_V4_VAR_TBL_ARRAY),

    SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_DIV        _TT(= IQ_CFG_REDO_AHD_DOT_EDGE_DIV),
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_MODE,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_SHR,


	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_SHR_THR,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT0,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT1,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT2,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT3,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT4,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT5,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT6,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_LUT7,

	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_WIDTH,
	SP5K_IQ_CFG_REDO_AHD_DOT_EDGE_THR,
	SP5K_IQ_CFG_REDO_AHD_DOT_MAX_NEG_AMP,
	SP5K_IQ_CFG_REDO_AHD_DOT_MAX_POS_AMP,
	SP5K_IQ_CFG_REDO_AHD_DOT_HF_MAX_NEG_AMP,
	SP5K_IQ_CFG_REDO_AHD_DOT_HF_MAX_POS_AMP,

	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_OPT,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT0,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT1,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT2,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT3,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT4,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT5,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT6,
	SP5K_IQ_CFG_REDO_AHD_DOT_NOISE_SHR_LUT7,


	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT0,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT1,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT2,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT3,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT4,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT5,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT6,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT7,
	SP5K_IQ_CFG_REDO_AHD_GRAY_Y_LUT8,


	SP5K_IQ_CFG_REDO_AHD_GRAY_LEVEL0,
	SP5K_IQ_CFG_REDO_AHD_GRAY_LEVEL1,
	SP5K_IQ_CFG_REDO_AHD_GRAY_LEVEL2,
	SP5K_IQ_CFG_REDO_AHD_GRAY_LEVEL3,
	SP5K_IQ_CFG_REDO_AHD_GRAY_LEVEL4,

	SP5K_IQ_CFG_REDO_AHD_COR_EN_LEVEL0,
	SP5K_IQ_CFG_REDO_AHD_COR_EN_LEVEL1,
	SP5K_IQ_CFG_REDO_AHD_COR_EN_LEVEL2,
	SP5K_IQ_CFG_REDO_AHD_COR_EN_LEVEL3,
	SP5K_IQ_CFG_REDO_AHD_COR_EN_LEVEL4,

	SP5K_IQ_CFG_REDO_AHD_GRAY_EN_LEVEL0,
	SP5K_IQ_CFG_REDO_AHD_GRAY_EN_LEVEL1,
	SP5K_IQ_CFG_REDO_AHD_GRAY_EN_LEVEL2,
	SP5K_IQ_CFG_REDO_AHD_GRAY_EN_LEVEL3,
	SP5K_IQ_CFG_REDO_AHD_GRAY_EN_LEVEL4,

	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_MIN_THR_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_THR3_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR3_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR3_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_THR3_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR3_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR3_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_THR2_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR2_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR2_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_THR2_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR2_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR2_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_THR1_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR1_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR1_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_THR1_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_THR1_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_THR1_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL3_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL2_V4,

	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_U0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_U2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_U4,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_V0,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_V2,
	SP5K_IQ_CFG_REDO_AHD_COR_VAL1_V4,

	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_THR,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_U0,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_U1,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_U2,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_U3,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_U4,

	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_V0,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_V1,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_V2,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_V3,
	SP5K_IQ_CFG_REDO_AHD_GRAY_MIN_V4,

	SP5K_IQ_CFG_REDO_AHD_Y_OFS,
	SP5K_IQ_CFG_REDO_AHD_U_OFS,
	SP5K_IQ_CFG_REDO_AHD_V_OFS,

	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_Y_GAIN_0,
	SP5K_IQ_CFG_REDO_AHD_SPK_VAR_Y_GAIN_3,

	SP5K_IQ_CFG_REDO_AHD_MAX,

	/* AHD Y cornor denoise*/
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_RATIO_EN   _TT(= IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_RATIO_EN),
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_RATIO,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_IDX_OFS,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_STEP1,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_STEP2,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_CX,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_CY,

	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_DEG1,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_DEG2,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_DEG3,
	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_DEG4,

	SP5K_IQ_CFG_REDO_AHD_Y_CORNER_DENOISE_MAX,

	/* AHD UV cornor denoise*/
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_RATIO_EN  _TT(= IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_RATIO_EN),
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_RATIO,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_IDX_OFS,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_STEP1,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_STEP2,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_CX,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_CY,

	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_DEG1,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_DEG2,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_DEG3,
	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_DEG4,

	SP5K_IQ_CFG_REDO_AHD_UV_CORNER_DENOISE_MAX,

	/* yef/ynf */
	SP5K_IQ_CFG_REDO_YEF_FILTER                      _TT(= IQ_CFG_REDO_YEF_FILTER),
	SP5K_IQ_CFG_REDO_YEF_EDGE_PATTERN,
	SP5K_IQ_CFG_REDO_YEF_YNF_THR,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_DIV,
	SP5K_IQ_CFG_REDO_YNF_EDGE_SHR_THR,
	SP5K_IQ_CFG_REDO_YEF5_FILT_OPT,
	SP5K_IQ_CFG_REDO_YEF3_FILT_OPT,
    SP5K_IQ_CFG_REDO_YEF_YNF_VAR_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SCL_FACTOR,
	SP5K_IQ_CFG_REDO_YEF_YNF_Y_EDGE_TRANS_W,
	SP5K_IQ_CFG_REDO_YNF_FILT_OPT,
	SP5K_IQ_CFG_REDO_YEF5_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_REDO_YEF3_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_REDO_YEF_EDGE_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_REDO_YEF_YNF_DIR_STRENGTH_LEVEL,
	SP5K_IQ_CFG_REDO_YEF_YNF_WT_STRENGTH_LEVEL,
	SP5K_IQ_CFG_REDO_YEF_YNF_STRONG_EDGE_LOW_THR,
	SP5K_IQ_CFG_REDO_YEF_YNF_OUT_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_REDO_YEF_YNF_WEAK_EDGE_LOW_THR,
	SP5K_IQ_CFG_REDO_YEF_YNF_WEAK_EDGE_VAR_THR,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL0,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL1,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL2,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL3,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL4,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL5,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL6,
	SP5K_IQ_CFG_REDO_YEF_YNF_EDGE_SHR_TBL7,

	SP5K_IQ_CFG_REDO_YEF_MAX,

	/* y edge */
	SP5K_IQ_CFG_REDO_Y_EDGE_SCALE                    _TT(= IQ_CFG_REDO_Y_EDGE_SCALE),
	SP5K_IQ_CFG_REDO_Y_EDGE_INDEX,
	SP5K_IQ_CFG_REDO_Y_EDGE_MAP_SCALE,

	SP5K_IQ_CFG_REDO_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_REDO_Y_EDGE_HIGH_THR,

	SP5K_IQ_CFG_REDO_Y_EDGE_YH_GAIN,
	SP5K_IQ_CFG_REDO_Y_EDGE_FINAL_LOW_THR,
	SP5K_IQ_CFG_REDO_Y_EDGE_FINAL_HIGH_THR,

	SP5K_IQ_CFG_REDO_Y_EDGE_FW_GAIN,

	SP5K_IQ_CFG_REDO_Y_EDGE_FILTER_ARRAY             _TT(= IQ_CFG_REDO_Y_EDGE_FILTER_ARRAY),
	SP5K_IQ_CFG_REDO_Y_EDGE_GAIN_ARRAY               _TT(= IQ_CFG_REDO_Y_EDGE_GAIN_ARRAY),

	SP5K_IQ_CFG_REDO_Y_EDGE_MAX,

	/* y corner edge */
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_RATIO_SEL         _TT(= IQ_CFG_REDO_Y_CORNER_EDGE_RATIO_SEL),
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_RATIO,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_IDX_OFFSET,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_STEP1,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_STEP2,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_CX,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_CY,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_EG1,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_EG2,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_EG3,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_EG4,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_P_FAC,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_N_FAC,
	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_MASK,

	SP5K_IQ_CFG_REDO_Y_CORNER_EDGE_MAX,

	/* uv core */
	SP5K_IQ_CFG_REDO_UV_CORE_U_MIN                   _TT(= IQ_CFG_REDO_UV_CORE_U_MIN),
	SP5K_IQ_CFG_REDO_UV_CORE_V_MIN,
	SP5K_IQ_CFG_REDO_UV_CORE_U_THR,
	SP5K_IQ_CFG_REDO_UV_CORE_V_THR,
	SP5K_IQ_CFG_REDO_UV_CORE_U_SHR,
	SP5K_IQ_CFG_REDO_UV_CORE_V_SHR,

	/* uv lpf */
	SP5K_IQ_CFG_REDO_UV_LPF_MODE                     _TT(= IQ_CFG_REDO_UV_LPF_MODE),
	SP5K_IQ_CFG_REDO_UV_LPF_RND_MODE,

	SP5K_IQ_CFG_REDO_UV_LPF_DIR_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_REDO_UV_LPF_AREA_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_REDO_UV_LPF_THR,
	SP5K_IQ_CFG_REDO_UV_LPF_DIR_MEDIAN_SEL,
	SP5K_IQ_CFG_REDO_UV_LPF_AREA_MEDIAN_SEL,

	SP5K_IQ_CFG_REDO_UV_LPF_SUP_EDGE_DIV,

	SP5K_IQ_CFG_REDO_UV_LPF_DIR_MODE,
	SP5K_IQ_CFG_REDO_UV_LPF_AREA_MODE,
	SP5K_IQ_CFG_REDO_UV_LPF_DIR_OPT,
	SP5K_IQ_CFG_REDO_UV_LPF_DIR_PAT_SEL,
	SP5K_IQ_CFG_REDO_UV_LPF_CNFY_MIN_SCL_FACT,
	SP5K_IQ_CFG_REDO_UV_LPF_Y_THR,
	SP5K_IQ_CFG_REDO_UV_LPF_Y_WIDTH,

	SP5K_IQ_CFG_REDO_UV_LPF_ARRAY                    _TT(= IQ_CFG_REDO_UV_LPF_ARRAY),

	SP5K_IQ_CFG_REDO_UV_LPF_MAX,

	/*YUV depeak*/
	SP5K_IQ_CFG_REDO_YUV_DEPEAK_OPT0                  _TT(= IQ_CFG_REDO_YUV_DEPEAK_OPT0),
	SP5K_IQ_CFG_REDO_YUV_DEPEAK_OPT1,
	SP5K_IQ_CFG_REDO_YUV_DEPEAK_MODE,

	/* digital effect */
	SP5K_IQ_CFG_REDO_DIGI_EFF_SOBEL_MASK_SEL         _TT(= IQ_CFG_REDO_DIGI_EFF_SOBEL_MASK_SEL),
	SP5K_IQ_CFG_REDO_DIGI_EFF_SOBEL_RIGHT_SHIFT,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_MODE_EN,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_MODE  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_RATIO  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_LIGHT  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_DEPTH  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECY1_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECY1_MODE  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECY2_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECU_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECV_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECY_SHIFT_BYTE ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_ECUV_SHIFT_BYTE  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_BRIGHT  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_U_BRIGHT  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_V_BRIGHT  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_CONTRAST  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_U_CONTRAST  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_V_CONTRAST  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_OFFSET  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_U_OFFSET  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_V_OFFSET  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_LOW_THR  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_HI_THR  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_VAL_SEL ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_DISTURB_VAL_MODE ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_NOR_Y_DISTURB  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_FACTOR1  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_FACTOR2  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_LUT_EN ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_UV_MATRIX_EN ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_Y_LUT_SEL ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_UV_MATRIX_ARRAY        _TT(= IQ_CFG_REDO_DIGI_EFF_UV_MATRIX_ARRAY),
	SP5K_IQ_CFG_REDO_DIGI_EFF_BI_EN                  _TT(= IQ_CFG_REDO_DIGI_EFF_BI_EN),
	SP5K_IQ_CFG_REDO_DIGI_EFF_BI_MODE_SEL ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_BI_Y1_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_BI_Y2_SEL  ,
	SP5K_IQ_CFG_REDO_DIGI_EFF_BI_THR  ,

	SP5K_IQ_CFG_REDO_DIGI_EFF_MAX,

	/* purple fringing*/
	SP5K_IQ_CFG_REDO_PURPLE_FRING_SOBEL_MODE         _TT(= IQ_CFG_REDO_PURPLE_FRING_SOBEL_MODE),
	SP5K_IQ_CFG_REDO_PURPLE_FRING_BLUR_SIZE,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_NORM_FACTOR,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_NORM_SHIFT,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_UV_EDGE0,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_UV_EDGE1,

	SP5K_IQ_CFG_REDO_PURPLE_FRING_UV_EDGE_THR,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_EPS_EXT_SIZE,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_EPS_U_THR,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_EPS_V_THR,

	SP5K_IQ_CFG_REDO_PURPLE_FRING_BLUR_THR,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_BLUR_FACTOR,
	SP5K_IQ_CFG_REDO_PURPLE_FRING_BLUR_SHIFT,

	SP5K_IQ_CFG_REDO_PURPLE_FRING_MAX,

	/* Sdo hue correction */
	SP5K_IQ_CFG_SDO_HUE_CLAMP_U               _TT(= IQ_CFG_SDO_HUE_CLAMP_U),
	SP5K_IQ_CFG_SDO_HUE_CLAMP_V,

	SP5K_IQ_CFG_SDO_HUE_LOW_THR,
	SP5K_IQ_CFG_SDO_HUE_WIN_WEIGHT,

	/* Sdo Y Gamma*/
	SP5K_IQ_CFG_SDO_Y_GAMMA_OFS               _TT(= IQ_CFG_SDO_Y_GAMMA_OFS),
	SP5K_IQ_CFG_SDO_Y_GAMMA_INVERSE_EN,

	/* Sdo wdr */
	SP5K_IQ_CFG_SDO_WDR_MODE                  _TT(= IQ_CFG_SDO_WDR_MODE),
	SP5K_IQ_CFG_SDO_WDR_Q_SCALE_FACTOR,
	SP5K_IQ_CFG_SDO_WDR_Q_ENHANCE_SCALE_FACTOR,

	SP5K_IQ_CFG_SDO_WDR_CONTRAST_GAIN,
	SP5K_IQ_CFG_SDO_WDR_CONTRAST_OFS,

	SP5K_IQ_CFG_SDO_WDR_Q_LUT_ARRAY           _TT(= IQ_CFG_SDO_WDR_Q_LUT_ARRAY),
	SP5K_IQ_CFG_SDO_WDR_U_THR_LUT_ARRAY       _TT(= IQ_CFG_SDO_WDR_U_THR_LUT_ARRAY),
	SP5K_IQ_CFG_SDO_WDR_V_THR_LUT_ARRAY       _TT(= IQ_CFG_SDO_WDR_V_THR_LUT_ARRAY),

	SP5K_IQ_CFG_SDO_WDR_MAX,

	/* Sdo aa */
	SP5K_IQ_CFG_SDO_AA_MODE                   _TT(= IQ_CFG_SDO_AA_MODE),
	SP5K_IQ_CFG_SDO_AA_UV_MODE,
	SP5K_IQ_CFG_SDO_AA_CLAMP_U,
	SP5K_IQ_CFG_SDO_AA_CLAMP_V,

	SP5K_IQ_CFG_SDO_AA_THR,
	SP5K_IQ_CFG_SDO_AA_X_SUB,
	SP5K_IQ_CFG_SDO_AA_Y_SUB,

	SP5K_IQ_CFG_SDO_AA_SHRINK_MODE,
	SP5K_IQ_CFG_SDO_AA_SHRINK_SCALE,

	SP5K_IQ_CFG_SDO_AA_STRNGTH_LEVEL,
	SP5K_IQ_CFG_SDO_AA_STRNGTH_WEIGHT,

	SP5K_IQ_CFG_SDO_AA_MAX,

	/* Sdo ahd */
	SP5K_IQ_CFG_SDO_AHD_SCL_DOWN_ROUND_MODE  _TT(= IQ_CFG_SDO_AHD_SCL_DOWN_ROUND_MODE),
	SP5K_IQ_CFG_SDO_AHD_SCL_UP_ROUND_MODE,
	SP5K_IQ_CFG_SDO_AHD_LEVEL4_EN,

	SP5K_IQ_CFG_SDO_AHD_UV_RATIO,

	SP5K_IQ_CFG_SDO_AHD_Y4_IIR_EN,
	SP5K_IQ_CFG_SDO_AHD_UV4_IIR_EN,

	SP5K_IQ_CFG_SDO_AHD_Y4_LEVEL_EN,
	SP5K_IQ_CFG_SDO_AHD_UV4_LEVEL_EN,

	SP5K_IQ_CFG_SDO_AHD_DENOISE_MODE,
	SP5K_IQ_CFG_SDO_AHD_UV_AVERAGE_EN,

	SP5K_IQ_CFG_SDO_AHD_Y4_HF_MODE0,
	SP5K_IQ_CFG_SDO_AHD_Y4_HF_MODE1,
	SP5K_IQ_CFG_SDO_AHD_UV4_HF_MODE,

	SP5K_IQ_CFG_SDO_AHD_Y4_BLUR_MASK_OPT,
	SP5K_IQ_CFG_SDO_AHD_UV4_BLUR_MASK_OPT,

	SP5K_IQ_CFG_SDO_AHD_Y4_SCL,
	SP5K_IQ_CFG_SDO_AHD_U4_SCL,
	SP5K_IQ_CFG_SDO_AHD_V4_SCL,

	SP5K_IQ_CFG_SDO_AHD_Y4_CONST_GAIN,
	SP5K_IQ_CFG_SDO_AHD_U4_CONST_GAIN,
	SP5K_IQ_CFG_SDO_AHD_V4_CONST_GAIN,

	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_PARAM3,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_PARAM2,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_PARAM1,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_PARAM0,

	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_PARAM3,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_PARAM2,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_PARAM1,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_PARAM0,

	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_SDO_AHD_Y4_LOW_THR_POS_HF_THR2,

	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_HF_THR3,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_HF_THR2,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_NEG_HF_THR1,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_HF_THR0,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_HF_THR1,
	SP5K_IQ_CFG_SDO_AHD_UV4_LOW_THR_POS_HF_THR2,

    SP5K_IQ_CFG_SDO_AHD_Y4_HI_THR,
    SP5K_IQ_CFG_SDO_AHD_UV4_HI_THR,

	SP5K_IQ_CFG_SDO_AHD_SPK_OPT2_Y4,
	SP5K_IQ_CFG_SDO_AHD_SPK_OPT3_Y4,

	SP5K_IQ_CFG_SDO_AHD_SPK_OPT2_UV4,
	SP5K_IQ_CFG_SDO_AHD_SPK_OPT3_UV4,

	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_Y_GAIN,
	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_U_GAIN,
	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_V_GAIN,
	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_U4_GAIN,
	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_V4_GAIN,

	SP5K_IQ_CFG_SDO_AHD_SHR_Y4_GAIN,
	SP5K_IQ_CFG_SDO_AHD_SHR_UV4_GAIN,

	SP5K_IQ_CFG_SDO_AHD_Y4_SCL_FACTOR,
	SP5K_IQ_CFG_SDO_AHD_UV4_SCL_FACTOR,

	SP5K_IQ_CFG_SDO_AHD_Y_HF_VAR_GAIN,
	SP5K_IQ_CFG_SDO_AHD_U_HF_VAR_GAIN,
	SP5K_IQ_CFG_SDO_AHD_V_HF_VAR_GAIN,

	SP5K_IQ_CFG_SDO_AHD_Y4_VAR_TBL_ARRAY    _TT(= IQ_CFG_SDO_AHD_Y4_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_SDO_AHD_U4_VAR_TBL_ARRAY    _TT(= IQ_CFG_SDO_AHD_U4_VAR_TBL_ARRAY),
	SP5K_IQ_CFG_SDO_AHD_V4_VAR_TBL_ARRAY    _TT(= IQ_CFG_SDO_AHD_V4_VAR_TBL_ARRAY),

    SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_DIV        _TT(= IQ_CFG_SDO_AHD_DOT_EDGE_DIV),
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_MODE,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_SHR,


	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_SHR_THR,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT0,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT1,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT2,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT3,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT4,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT5,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT6,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_LUT7,

	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_WIDTH,
	SP5K_IQ_CFG_SDO_AHD_DOT_EDGE_THR,
	SP5K_IQ_CFG_SDO_AHD_DOT_MAX_NEG_AMP,
	SP5K_IQ_CFG_SDO_AHD_DOT_MAX_POS_AMP,
	SP5K_IQ_CFG_SDO_AHD_DOT_HF_MAX_NEG_AMP,
	SP5K_IQ_CFG_SDO_AHD_DOT_HF_MAX_POS_AMP,

	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_OPT,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT0,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT1,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT2,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT3,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT4,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT5,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT6,
	SP5K_IQ_CFG_SDO_AHD_DOT_NOISE_SHR_LUT7,


	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT0,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT1,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT2,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT3,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT4,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT5,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT6,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT7,
	SP5K_IQ_CFG_SDO_AHD_GRAY_Y_LUT8,


	SP5K_IQ_CFG_SDO_AHD_GRAY_LEVEL4,
	SP5K_IQ_CFG_SDO_AHD_COR_EN_LEVEL4,
	SP5K_IQ_CFG_SDO_AHD_GRAY_EN_LEVEL4,

	SP5K_IQ_CFG_SDO_AHD_COR_MIN_THR_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_MIN_THR_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_THR3_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_THR3_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_THR2_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_THR2_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_THR1_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_THR1_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_VAL3_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_VAL3_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_VAL2_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_VAL2_V4,

	SP5K_IQ_CFG_SDO_AHD_COR_VAL1_U4,
	SP5K_IQ_CFG_SDO_AHD_COR_VAL1_V4,

	SP5K_IQ_CFG_SDO_AHD_GRAY_MIN_THR,
	SP5K_IQ_CFG_SDO_AHD_GRAY_MIN_U4,
	SP5K_IQ_CFG_SDO_AHD_GRAY_MIN_V4,

	SP5K_IQ_CFG_SDO_AHD_Y_OFS,
	SP5K_IQ_CFG_SDO_AHD_U_OFS,
	SP5K_IQ_CFG_SDO_AHD_V_OFS,

	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_Y_GAIN_0,
	SP5K_IQ_CFG_SDO_AHD_SPK_VAR_Y_GAIN_3,

	SP5K_IQ_CFG_SDO_AHD_MAX,

	/* Sdo yef/ynf */
	SP5K_IQ_CFG_SDO_YEF_FILTER                      _TT(= IQ_CFG_SDO_YEF_FILTER),
	SP5K_IQ_CFG_SDO_YEF_EDGE_PATTERN,
	SP5K_IQ_CFG_SDO_YEF_YNF_THR,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_DIV,
	SP5K_IQ_CFG_SDO_YNF_EDGE_SHR_THR,
	SP5K_IQ_CFG_SDO_YEF5_FILT_OPT,
	SP5K_IQ_CFG_SDO_YEF3_FILT_OPT,
    SP5K_IQ_CFG_SDO_YEF_YNF_VAR_SCL_FACTOR,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SCL_FACTOR,
	SP5K_IQ_CFG_SDO_YEF_YNF_Y_EDGE_TRANS_W,
	SP5K_IQ_CFG_SDO_YNF_FILT_OPT,
	SP5K_IQ_CFG_SDO_YEF5_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_SDO_YEF3_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_SDO_YEF_EDGE_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_SDO_YEF_YNF_DIR_STRENGTH_LEVEL,
	SP5K_IQ_CFG_SDO_YEF_YNF_WT_STRENGTH_LEVEL,
	SP5K_IQ_CFG_SDO_YEF_YNF_STRONG_EDGE_LOW_THR,
	SP5K_IQ_CFG_SDO_YEF_YNF_OUT_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_SDO_YEF_YNF_WEAK_EDGE_LOW_THR,
	SP5K_IQ_CFG_SDO_YEF_YNF_WEAK_EDGE_VAR_THR,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL0,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL1,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL2,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL3,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL4,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL5,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL6,
	SP5K_IQ_CFG_SDO_YEF_YNF_EDGE_SHR_TBL7,

	SP5K_IQ_CFG_SDO_YEF_MAX,

	/* Sdo y edge */
	SP5K_IQ_CFG_SDO_Y_EDGE_SCALE                    _TT(= IQ_CFG_SDO_Y_EDGE_SCALE),
	SP5K_IQ_CFG_SDO_Y_EDGE_INDEX,
	SP5K_IQ_CFG_SDO_Y_EDGE_MAP_SCALE,

	SP5K_IQ_CFG_SDO_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_SDO_Y_EDGE_HIGH_THR,

	SP5K_IQ_CFG_SDO_Y_EDGE_YH_GAIN,
	SP5K_IQ_CFG_SDO_Y_EDGE_FINAL_LOW_THR,
	SP5K_IQ_CFG_SDO_Y_EDGE_FINAL_HIGH_THR,

	SP5K_IQ_CFG_SDO_Y_EDGE_FW_GAIN,

	SP5K_IQ_CFG_SDO_Y_EDGE_FILTER_ARRAY             _TT(= IQ_CFG_SDO_Y_EDGE_FILTER_ARRAY),
	SP5K_IQ_CFG_SDO_Y_EDGE_GAIN_ARRAY               _TT(= IQ_CFG_SDO_Y_EDGE_GAIN_ARRAY),

	SP5K_IQ_CFG_SDO_Y_EDGE_MAX,

	/* Sdo y corner edge */
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_RATIO_SEL         _TT(= IQ_CFG_SDO_Y_CORNER_EDGE_RATIO_SEL),
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_RATIO,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_IDX_OFFSET,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_STEP1,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_STEP2,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_CX,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_CY,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_EG1,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_EG2,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_EG3,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_EG4,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_P_FAC,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_N_FAC,
	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_MASK,

	SP5K_IQ_CFG_SDO_Y_CORNER_EDGE_MAX,

	/* Sdo uv core */
	SP5K_IQ_CFG_SDO_UV_CORE_U_MIN                   _TT(= IQ_CFG_SDO_UV_CORE_U_MIN),
	SP5K_IQ_CFG_SDO_UV_CORE_V_MIN,
	SP5K_IQ_CFG_SDO_UV_CORE_U_THR,
	SP5K_IQ_CFG_SDO_UV_CORE_V_THR,
	SP5K_IQ_CFG_SDO_UV_CORE_U_SHR,
	SP5K_IQ_CFG_SDO_UV_CORE_V_SHR,

	/* Sdo uv lpf */
	SP5K_IQ_CFG_SDO_UV_LPF_MODE                     _TT(= IQ_CFG_SDO_UV_LPF_MODE),
	SP5K_IQ_CFG_SDO_UV_LPF_RND_MODE,

	SP5K_IQ_CFG_SDO_UV_LPF_DIR_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_SDO_UV_LPF_AREA_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_SDO_UV_LPF_THR,
	SP5K_IQ_CFG_SDO_UV_LPF_DIR_MEDIAN_SEL,
	SP5K_IQ_CFG_SDO_UV_LPF_AREA_MEDIAN_SEL,

	SP5K_IQ_CFG_SDO_UV_LPF_SUP_EDGE_DIV,

	SP5K_IQ_CFG_SDO_UV_LPF_DIR_MODE,
	SP5K_IQ_CFG_SDO_UV_LPF_AREA_MODE,
	SP5K_IQ_CFG_SDO_UV_LPF_DIR_OPT,
	SP5K_IQ_CFG_SDO_UV_LPF_DIR_PAT_SEL,
	SP5K_IQ_CFG_SDO_UV_LPF_CNFY_MIN_SCL_FACT,
	SP5K_IQ_CFG_SDO_UV_LPF_Y_THR,
	SP5K_IQ_CFG_SDO_UV_LPF_Y_WIDTH,

	SP5K_IQ_CFG_SDO_UV_LPF_ARRAY                    _TT(= IQ_CFG_SDO_UV_LPF_ARRAY),

	SP5K_IQ_CFG_SDO_UV_LPF_MAX,

	/* Sdo YUV depeak*/
	SP5K_IQ_CFG_SDO_YUV_DEPEAK_OPT0                  _TT(= IQ_CFG_SDO_YUV_DEPEAK_OPT0),
	SP5K_IQ_CFG_SDO_YUV_DEPEAK_OPT1,
	SP5K_IQ_CFG_SDO_YUV_DEPEAK_MODE,

	/* Sdo digital effect */
	SP5K_IQ_CFG_SDO_DIGI_EFF_SOBEL_MASK_SEL         _TT(= IQ_CFG_SDO_DIGI_EFF_SOBEL_MASK_SEL),
	SP5K_IQ_CFG_SDO_DIGI_EFF_SOBEL_RIGHT_SHIFT,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_MODE_EN,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_MODE  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_RATIO  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_LIGHT  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_DEPTH  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECY1_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECY1_MODE  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECY2_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECU_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECV_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECY_SHIFT_BYTE ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_ECUV_SHIFT_BYTE  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_BRIGHT  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_U_BRIGHT  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_V_BRIGHT  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_CONTRAST  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_U_CONTRAST  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_V_CONTRAST  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_OFFSET  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_U_OFFSET  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_V_OFFSET  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_LOW_THR  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_HI_THR  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_VAL_SEL ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_DISTURB_VAL_MODE ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_NOR_Y_DISTURB  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_FACTOR1  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_FACTOR2  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_LUT_EN ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_UV_MATRIX_EN ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_Y_LUT_SEL ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_UV_MATRIX_ARRAY        _TT(= IQ_CFG_SDO_DIGI_EFF_UV_MATRIX_ARRAY),
	SP5K_IQ_CFG_SDO_DIGI_EFF_BI_EN                  _TT(= IQ_CFG_SDO_DIGI_EFF_BI_EN),
	SP5K_IQ_CFG_SDO_DIGI_EFF_BI_MODE_SEL ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_BI_Y1_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_BI_Y2_SEL  ,
	SP5K_IQ_CFG_SDO_DIGI_EFF_BI_THR  ,

	SP5K_IQ_CFG_SDO_DIGI_EFF_MAX,

	/* Sdo purple fringing*/
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_SOBEL_MODE         _TT(= IQ_CFG_SDO_PURPLE_FRINGE_SOBEL_MODE),
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_BLUR_SIZE,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_NORM_FACTOR,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_NORM_SHIFT,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_UV_EDGE0,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_UV_EDGE1,

	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_UV_EDGE_THR,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_EPS_EXT_SIZE,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_EPS_U_THR,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_EPS_V_THR,

	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_BLUR_THR,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_BLUR_FACTOR,
	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_BLUR_SHIFT,

	SP5K_IQ_CFG_SDO_PURPLE_FRINGE_MAX,

	/* S22do hue correction */
	SP5K_IQ_CFG_S2DO_HUE_CLAMP_U               _TT(= IQ_CFG_S2DO_HUE_CLAMP_U),
	SP5K_IQ_CFG_S2DO_HUE_CLAMP_V,

	SP5K_IQ_CFG_S2DO_HUE_LOW_THR,
	SP5K_IQ_CFG_S2DO_HUE_WIN_WEIGHT,

	/* S2do Y Gamma*/
	SP5K_IQ_CFG_S2DO_Y_GAMMA_OFS               _TT(= IQ_CFG_S2DO_Y_GAMMA_OFS),
	SP5K_IQ_CFG_S2DO_Y_GAMMA_INVERSE_EN,

	/* S2do wdr */
	SP5K_IQ_CFG_S2DO_WDR_MODE                  _TT(= IQ_CFG_S2DO_WDR_MODE),
	SP5K_IQ_CFG_S2DO_WDR_Q_SCALE_FACTOR,
	SP5K_IQ_CFG_S2DO_WDR_Q_ENHANCE_SCALE_FACTOR,

	SP5K_IQ_CFG_S2DO_WDR_CONTRAST_GAIN,
	SP5K_IQ_CFG_S2DO_WDR_CONTRAST_OFS,

	SP5K_IQ_CFG_S2DO_WDR_Q_LUT_ARRAY           _TT(= IQ_CFG_S2DO_WDR_Q_LUT_ARRAY),
	SP5K_IQ_CFG_S2DO_WDR_U_THR_LUT_ARRAY       _TT(= IQ_CFG_S2DO_WDR_U_THR_LUT_ARRAY),
	SP5K_IQ_CFG_S2DO_WDR_V_THR_LUT_ARRAY       _TT(= IQ_CFG_S2DO_WDR_V_THR_LUT_ARRAY),

	SP5K_IQ_CFG_S2DO_WDR_MAX,

	/* Sdo aa */
	SP5K_IQ_CFG_S2DO_AA_MODE                   _TT(= IQ_CFG_S2DO_AA_MODE),
	SP5K_IQ_CFG_S2DO_AA_UV_MODE,
	SP5K_IQ_CFG_S2DO_AA_CLAMP_U,
	SP5K_IQ_CFG_S2DO_AA_CLAMP_V,

	SP5K_IQ_CFG_S2DO_AA_THR,
	SP5K_IQ_CFG_S2DO_AA_X_SUB,
	SP5K_IQ_CFG_S2DO_AA_Y_SUB,

	SP5K_IQ_CFG_S2DO_AA_SHRINK_MODE,
	SP5K_IQ_CFG_S2DO_AA_SHRINK_SCALE,

	SP5K_IQ_CFG_S2DO_AA_STRNGTH_LEVEL,
	SP5K_IQ_CFG_S2DO_AA_STRNGTH_WEIGHT,

	SP5K_IQ_CFG_S2DO_AA_MAX,

	/* Sdo yef/ynf */
	SP5K_IQ_CFG_S2DO_YEF_FILTER                      _TT(= IQ_CFG_S2DO_YEF_FILTER),
	SP5K_IQ_CFG_S2DO_YEF_EDGE_PATTERN,
	SP5K_IQ_CFG_S2DO_YEF_YNF_THR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_DIV,
	SP5K_IQ_CFG_S2DO_YNF_EDGE_SHR_THR,
	SP5K_IQ_CFG_S2DO_YEF5_FILT_OPT,
	SP5K_IQ_CFG_S2DO_YEF3_FILT_OPT,
    SP5K_IQ_CFG_S2DO_YEF_YNF_VAR_SCL_FACTOR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SCL_FACTOR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_Y_EDGE_TRANS_W,
	SP5K_IQ_CFG_S2DO_YNF_FILT_OPT,
	SP5K_IQ_CFG_S2DO_YEF5_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_S2DO_YEF3_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_S2DO_YEF_EDGE_FILT_WT_OFS_EN,
	SP5K_IQ_CFG_S2DO_YEF_YNF_DIR_STRENGTH_LEVEL,
	SP5K_IQ_CFG_S2DO_YEF_YNF_WT_STRENGTH_LEVEL,
	SP5K_IQ_CFG_S2DO_YEF_YNF_STRONG_EDGE_LOW_THR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_OUT_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_WEAK_EDGE_LOW_THR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_WEAK_EDGE_VAR_THR,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL0,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL1,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL2,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL3,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL4,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL5,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL6,
	SP5K_IQ_CFG_S2DO_YEF_YNF_EDGE_SHR_TBL7,

	SP5K_IQ_CFG_S2DO_YEF_MAX,

	/* Sdo y edge */
	SP5K_IQ_CFG_S2DO_Y_EDGE_SCALE                    _TT(= IQ_CFG_S2DO_Y_EDGE_SCALE),
	SP5K_IQ_CFG_S2DO_Y_EDGE_INDEX,
	SP5K_IQ_CFG_S2DO_Y_EDGE_MAP_SCALE,

	SP5K_IQ_CFG_S2DO_Y_EDGE_LOW_THR,
	SP5K_IQ_CFG_S2DO_Y_EDGE_HIGH_THR,

	SP5K_IQ_CFG_S2DO_Y_EDGE_YH_GAIN,
	SP5K_IQ_CFG_S2DO_Y_EDGE_FINAL_LOW_THR,
	SP5K_IQ_CFG_S2DO_Y_EDGE_FINAL_HIGH_THR,

	SP5K_IQ_CFG_S2DO_Y_EDGE_FW_GAIN,

	SP5K_IQ_CFG_S2DO_Y_EDGE_FILTER_ARRAY             _TT(= IQ_CFG_S2DO_Y_EDGE_FILTER_ARRAY),
	SP5K_IQ_CFG_S2DO_Y_EDGE_GAIN_ARRAY               _TT(= IQ_CFG_S2DO_Y_EDGE_GAIN_ARRAY),

	SP5K_IQ_CFG_S2DO_Y_EDGE_MAX,

	/* Sdo y corner edge */
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_RATIO_SEL         _TT(= IQ_CFG_S2DO_Y_CORNER_EDGE_RATIO_SEL),
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_RATIO,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_IDX_OFFSET,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_STEP1,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_STEP2,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_CX,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_CY,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_EG1,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_EG2,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_EG3,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_EG4,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_P_FAC,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_N_FAC,
	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_MASK,

	SP5K_IQ_CFG_S2DO_Y_CORNER_EDGE_MAX,

	/* Sdo uv core */
	SP5K_IQ_CFG_S2DO_UV_CORE_U_MIN                   _TT(= IQ_CFG_S2DO_UV_CORE_U_MIN),
	SP5K_IQ_CFG_S2DO_UV_CORE_V_MIN,
	SP5K_IQ_CFG_S2DO_UV_CORE_U_THR,
	SP5K_IQ_CFG_S2DO_UV_CORE_V_THR,
	SP5K_IQ_CFG_S2DO_UV_CORE_U_SHR,
	SP5K_IQ_CFG_S2DO_UV_CORE_V_SHR,

	/* Sdo uv lpf */
	SP5K_IQ_CFG_S2DO_UV_LPF_MODE                     _TT(= IQ_CFG_S2DO_UV_LPF_MODE),
	SP5K_IQ_CFG_S2DO_UV_LPF_RND_MODE,

	SP5K_IQ_CFG_S2DO_UV_LPF_DIR_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_S2DO_UV_LPF_AREA_MEDIAN_WEIGHTING,
	SP5K_IQ_CFG_S2DO_UV_LPF_THR,
	SP5K_IQ_CFG_S2DO_UV_LPF_DIR_MEDIAN_SEL,
	SP5K_IQ_CFG_S2DO_UV_LPF_AREA_MEDIAN_SEL,

	SP5K_IQ_CFG_S2DO_UV_LPF_SUP_EDGE_DIV,

	SP5K_IQ_CFG_S2DO_UV_LPF_DIR_MODE,
	SP5K_IQ_CFG_S2DO_UV_LPF_AREA_MODE,
	SP5K_IQ_CFG_S2DO_UV_LPF_DIR_OPT,
	SP5K_IQ_CFG_S2DO_UV_LPF_DIR_PAT_SEL,
	SP5K_IQ_CFG_S2DO_UV_LPF_CNFY_MIN_SCL_FACT,
	SP5K_IQ_CFG_S2DO_UV_LPF_Y_THR,
	SP5K_IQ_CFG_S2DO_UV_LPF_Y_WIDTH,

	SP5K_IQ_CFG_S2DO_UV_LPF_ARRAY                    _TT(= IQ_CFG_S2DO_UV_LPF_ARRAY),

	SP5K_IQ_CFG_S2DO_UV_LPF_MAX,

	/* Sdo YUV depeak*/
	SP5K_IQ_CFG_S2DO_YUV_DEPEAK_OPT0                  _TT(= IQ_CFG_S2DO_YUV_DEPEAK_OPT0),
	SP5K_IQ_CFG_S2DO_YUV_DEPEAK_OPT1,
	SP5K_IQ_CFG_S2DO_YUV_DEPEAK_MODE,

	/* Sdo digital effect */
	SP5K_IQ_CFG_S2DO_DIGI_EFF_SOBEL_MASK_SEL         _TT(= IQ_CFG_S2DO_DIGI_EFF_SOBEL_MASK_SEL),
	SP5K_IQ_CFG_S2DO_DIGI_EFF_SOBEL_RIGHT_SHIFT,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_MODE_EN,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_MODE  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_RATIO  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_LIGHT  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_DEPTH  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECY1_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECY1_MODE  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECY2_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECU_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECV_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECY_SHIFT_BYTE ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_ECUV_SHIFT_BYTE  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_BRIGHT  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_U_BRIGHT  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_V_BRIGHT  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_CONTRAST  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_U_CONTRAST  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_V_CONTRAST  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_OFFSET  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_U_OFFSET  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_V_OFFSET  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_LOW_THR  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_HI_THR  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_VAL_SEL ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_DISTURB_VAL_MODE ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_NOR_Y_DISTURB  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_FACTOR1  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_FACTOR2  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_LUT_EN ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_UV_MATRIX_EN ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_Y_LUT_SEL ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_UV_MATRIX_ARRAY        _TT(= IQ_CFG_S2DO_DIGI_EFF_UV_MATRIX_ARRAY),
	SP5K_IQ_CFG_S2DO_DIGI_EFF_BI_EN                  _TT(= IQ_CFG_S2DO_DIGI_EFF_BI_EN),
	SP5K_IQ_CFG_S2DO_DIGI_EFF_BI_MODE_SEL ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_BI_Y1_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_BI_Y2_SEL  ,
	SP5K_IQ_CFG_S2DO_DIGI_EFF_BI_THR  ,

	SP5K_IQ_CFG_S2DO_DIGI_EFF_MAX,

	/* Sdo purple fringing*/
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_SOBEL_MODE         _TT(= IQ_CFG_S2DO_PURPLE_FRINGE_SOBEL_MODE),
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_BLUR_SIZE,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_NORM_FACTOR,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_NORM_SHIFT,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_UV_EDGE0,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_UV_EDGE1,

	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_UV_EDGE_THR,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_EPS_EXT_SIZE,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_EPS_U_THR,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_EPS_V_THR,

	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_BLUR_THR,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_BLUR_FACTOR,
	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_BLUR_SHIFT,

	SP5K_IQ_CFG_S2DO_PURPLE_FRINGE_MAX,

	/* internal */
	SP5K_IQ_CFG_LDC_PARAM_PTR_INTERNAL          _TT(= IQ_CFG_LDC_PARAM_PTR_INTERNAL),

	/* misc */
	SP5K_IQ_CFG_ICAT_ANSMATCH                    _TT(= IQ_CFG_ICAT_ANSMATCH),
	SP5K_IQ_CFG_ICAT_JPG_CMP_RATIO,
	SP5K_IQ_CFG_ANR_YUV_BLEND_RATIO,
	SP5K_IQ_CFG_MISC_MAX,

	/* moe */
	SP5K_IQ_CFG_MOE_Y_MOE_LEVEL					_TT(= IQ_CFG_MOE_Y_MOE_LEVEL),
	SP5K_IQ_CFG_MOE_UV_MOE_LEVEL,
	SP5K_IQ_CFG_MOE_Y_SCL_FAC,
	SP5K_IQ_CFG_MOE_UV_SCL_FAC,

	SP5K_IQ_CFG_MOE_YEP_MSK_SZE_0,
	SP5K_IQ_CFG_MOE_YEP_MSK_SZE_1,
	SP5K_IQ_CFG_MOE_YEP_MSK_SZE_2,
	SP5K_IQ_CFG_MOE_CRCBEP_MSK_SZE_0,
	SP5K_IQ_CFG_MOE_CRCBEP_MSK_SZE_1,
	SP5K_IQ_CFG_MOE_CRCBEP_MSK_SZE_2,

	SP5K_IQ_CFG_MOE_2L_THR1_U6,
	SP5K_IQ_CFG_MOE_2L_THR1_U7,
	SP5K_IQ_CFG_MOE_2L_THR1_U8,
	SP5K_IQ_CFG_MOE_2L_THR1_V6,
	SP5K_IQ_CFG_MOE_2L_THR1_V7,
	SP5K_IQ_CFG_MOE_2L_THR1_V8,
	SP5K_IQ_CFG_MOE_2L_THR1_Y6,
	SP5K_IQ_CFG_MOE_2L_THR1_Y7,
	SP5K_IQ_CFG_MOE_2L_THR1_Y8,

	SP5K_IQ_CFG_MOE_2L_THR2_U6,
	SP5K_IQ_CFG_MOE_2L_THR2_U7,
	SP5K_IQ_CFG_MOE_2L_THR2_U8,
	SP5K_IQ_CFG_MOE_2L_THR2_V6,
	SP5K_IQ_CFG_MOE_2L_THR2_V7,
	SP5K_IQ_CFG_MOE_2L_THR2_V8,
	SP5K_IQ_CFG_MOE_2L_THR2_Y6,
	SP5K_IQ_CFG_MOE_2L_THR2_Y7,
	SP5K_IQ_CFG_MOE_2L_THR2_Y8,

	SP5K_IQ_CFG_MOE_2L_THR2V_U6,
	SP5K_IQ_CFG_MOE_2L_THR2V_U7,
	SP5K_IQ_CFG_MOE_2L_THR2V_U8,
	SP5K_IQ_CFG_MOE_2L_THR2V_V6,
	SP5K_IQ_CFG_MOE_2L_THR2V_V7,
	SP5K_IQ_CFG_MOE_2L_THR2V_V8,
	SP5K_IQ_CFG_MOE_2L_THR2V_Y6,
	SP5K_IQ_CFG_MOE_2L_THR2V_Y7,
	SP5K_IQ_CFG_MOE_2L_THR2V_Y8,

	SP5K_IQ_CFG_MOE_2L_THR3_U6,
	SP5K_IQ_CFG_MOE_2L_THR3_U7,
	SP5K_IQ_CFG_MOE_2L_THR3_U8,
	SP5K_IQ_CFG_MOE_2L_THR3_V6,
	SP5K_IQ_CFG_MOE_2L_THR3_V7,
	SP5K_IQ_CFG_MOE_2L_THR3_V8,
	SP5K_IQ_CFG_MOE_2L_THR3_Y6,
	SP5K_IQ_CFG_MOE_2L_THR3_Y7,
	SP5K_IQ_CFG_MOE_2L_THR3_Y8,

	SP5K_IQ_CFG_MOE_2L_THR3V_U6,
	SP5K_IQ_CFG_MOE_2L_THR3V_U7,
	SP5K_IQ_CFG_MOE_2L_THR3V_U8,
	SP5K_IQ_CFG_MOE_2L_THR3V_V6,
	SP5K_IQ_CFG_MOE_2L_THR3V_V7,
	SP5K_IQ_CFG_MOE_2L_THR3V_V8,
	SP5K_IQ_CFG_MOE_2L_THR3V_Y6,
	SP5K_IQ_CFG_MOE_2L_THR3V_Y7,
	SP5K_IQ_CFG_MOE_2L_THR3V_Y8,

	SP5K_IQ_CFG_MOE_2R_THR1_U6,
	SP5K_IQ_CFG_MOE_2R_THR1_U7,
	SP5K_IQ_CFG_MOE_2R_THR1_U8,
	SP5K_IQ_CFG_MOE_2R_THR1_V6,
	SP5K_IQ_CFG_MOE_2R_THR1_V7,
	SP5K_IQ_CFG_MOE_2R_THR1_V8,
	SP5K_IQ_CFG_MOE_2R_THR1_Y6,
	SP5K_IQ_CFG_MOE_2R_THR1_Y7,
	SP5K_IQ_CFG_MOE_2R_THR1_Y8,

	SP5K_IQ_CFG_MOE_2R_THR2_U6,
	SP5K_IQ_CFG_MOE_2R_THR2_U7,
	SP5K_IQ_CFG_MOE_2R_THR2_U8,
	SP5K_IQ_CFG_MOE_2R_THR2_V6,
	SP5K_IQ_CFG_MOE_2R_THR2_V7,
	SP5K_IQ_CFG_MOE_2R_THR2_V8,
	SP5K_IQ_CFG_MOE_2R_THR2_Y6,
	SP5K_IQ_CFG_MOE_2R_THR2_Y7,
	SP5K_IQ_CFG_MOE_2R_THR2_Y8,

	SP5K_IQ_CFG_MOE_2R_THR2V_U6,
	SP5K_IQ_CFG_MOE_2R_THR2V_U7,
	SP5K_IQ_CFG_MOE_2R_THR2V_U8,
	SP5K_IQ_CFG_MOE_2R_THR2V_V6,
	SP5K_IQ_CFG_MOE_2R_THR2V_V7,
	SP5K_IQ_CFG_MOE_2R_THR2V_V8,
	SP5K_IQ_CFG_MOE_2R_THR2V_Y6,
	SP5K_IQ_CFG_MOE_2R_THR2V_Y7,
	SP5K_IQ_CFG_MOE_2R_THR2V_Y8,

	SP5K_IQ_CFG_MOE_2R_THR3_U6,
	SP5K_IQ_CFG_MOE_2R_THR3_U7,
	SP5K_IQ_CFG_MOE_2R_THR3_U8,
	SP5K_IQ_CFG_MOE_2R_THR3_V6,
	SP5K_IQ_CFG_MOE_2R_THR3_V7,
	SP5K_IQ_CFG_MOE_2R_THR3_V8,
	SP5K_IQ_CFG_MOE_2R_THR3_Y6,
	SP5K_IQ_CFG_MOE_2R_THR3_Y7,
	SP5K_IQ_CFG_MOE_2R_THR3_Y8,

	SP5K_IQ_CFG_MOE_2R_THR3V_U6,
	SP5K_IQ_CFG_MOE_2R_THR3V_U7,
	SP5K_IQ_CFG_MOE_2R_THR3V_U8,
	SP5K_IQ_CFG_MOE_2R_THR3V_V6,
	SP5K_IQ_CFG_MOE_2R_THR3V_V7,
	SP5K_IQ_CFG_MOE_2R_THR3V_V8,
	SP5K_IQ_CFG_MOE_2R_THR3V_Y6,
	SP5K_IQ_CFG_MOE_2R_THR3V_Y7,
	SP5K_IQ_CFG_MOE_2R_THR3V_Y8,

	SP5K_IQ_CFG_MOE_S_BLEND_EN,
	SP5K_IQ_CFG_MOE_Y_LO_THR,
	SP5K_IQ_CFG_MOE_Y_HI_THR,
	SP5K_IQ_CFG_MOE_Y_LO_W,
	SP5K_IQ_CFG_MOE_S_LO_THR,
	SP5K_IQ_CFG_MOE_S_HI_THR,
	SP5K_IQ_CFG_MOE_S_LO_W,

	SP5K_IQ_CFG_MOE_S_BRICON_EN,
	SP5K_IQ_CFG_MOE_F_CONF,
	SP5K_IQ_CFG_MOE_S_BRI_OFF,
	SP5K_IQ_CFG_MOE_S_BIN_EN,
	SP5K_IQ_CFG_MOE_S_BIN_THR,
	SP5K_IQ_CFG_MOE_S_COL_EN,
	SP5K_IQ_CFG_MOE_F_SA00,
	SP5K_IQ_CFG_MOE_F_SA01,
	SP5K_IQ_CFG_MOE_F_SA10,
	SP5K_IQ_CFG_MOE_F_SA11,
	SP5K_IQ_CFG_MOE_S_CB_OFF,
	SP5K_IQ_CFG_MOE_S_CR_OFF,

	SP5K_IQ_CFG_MOE_MAX,

	SP5K_IQ_CFG_WDR8x8_EN              _TT(= IQ_CFG_WDR8x8_EN),
	SP5K_IQ_CFG_WDR8x8_BLK_CFG,
	SP5K_IQ_CFG_WDR8x8_Q_SCALE,
	SP5K_IQ_CFG_WDR8x8_ENHANCE,
	SP5K_IQ_CFG_WDR8x8_UV_THR,
	SP5K_IQ_CFG_WDR8x8_BLUE_EN,
	SP5K_IQ_CFG_WDR8x8_DARK_EN,
	SP5K_IQ_CFG_WDR8x8_ISO_VALUE,
	SP5K_IQ_CFG_WDR8x8_LV_TBL,
	SP5K_IQ_CFG_WDR8x8_BRIGHTNESS_TBL,

	SP5K_IQ_CFG_WDR8x8_MAX,

} sp5kIqCfgSelector_t;
#undef _TT

/* SP5K_IQ_CFG_OB_MODE */
#define SP5K_OB_MANUAL		0
#define SP5K_OB_AUTO		1
#define SP5K_OB_AUTO_AVG	2

#ifdef _WINDOWS_
	#define SP5K_RES_AUTO (-1)
	/* here define it again to avoid including "sp5k_rsvblk_api.h" and all files implicated by it in iCatTune app */
#endif

#define SP5K_IQ_LUT_OPT_ALLOCATED	(1<<0)
#define SP5K_IQ_LUT_OPT_STATIC		(0<<0)

typedef enum sp5kSenId_e {
	SP5K_SEN_ID_0,
	SP5K_SEN_ID_1,
	SP5K_SEN_ID_MAX
} sp5kSenId_t;

typedef enum sp5kIqCapability_e {
	SP5K_IQ_CPB_TOTAL_IQ_SET,
	SP5K_IQ_CPB_MAX
} sp5kIqCapability_t;

/**************************************************************************
 *                          D A T A    T Y P E S                          *
 **************************************************************************/

/**************************************************************************
 *                               M A C R O S                              *
 **************************************************************************/

 /**************************************************************************
 *               F U N C T I O N    D E C L A R A T I O N S               *
 **************************************************************************/
/* 5330 new api */
/*#if !defined(_WINDOWS_) */
UINT32 sp5kIqCfgSet( sp5kIqCfgSelector_t id, UINT32 value );
UINT32 sp5kIqCfgGet( sp5kIqCfgSelector_t id, UINT32 * value );
UINT32 sp5kIqCfgDebugSet(sp5kIqCfgSelector_t id);
UINT32 sp5kIqLutDiqSet( UINT32 resId, UINT8 * buf, UINT32 size, UINT32 option );
UINT32 sp5kIqBlockEnable( sp5kIqBlocklSelector_t selector, UINT32 enable );
UINT32 sp5kIqBlockEnableGet( sp5kIqBlocklSelector_t selector, UINT32 * enable );
UINT32 sp5kIqBlockEnDebugSet(sp5kIqBlocklSelector_t selector);
UINT32 sp5kIqModeSet( UINT32 mode5k );
UINT32 sp5kIqModeSetExt(sp5kSenId_t senId, UINT32 mode5k );
UINT32 sp5kIqModeSetDone( UINT32 mode5k );
UINT32 sp5kIqModeSetDoneExt( sp5kSenId_t senId, UINT32 mode5k );
UINT32 sp5kIqModeGet( void );

UINT32 sp5kIqCfgParamInfoQuery( UINT32 selector, UINT32 * lenInfo );
UINT32 sp5kIqCfgSetInfoQuery( UINT32 selector, UINT32 * lenInfo );
UINT32 sp5kIqCfgGetInfoQuery( UINT32 selector, UINT32 * lenInfo );
void sp5kIqCdspRegToFile( UINT32 id );
void sp5kIqCdspResToFile( UINT32 id );
UINT32 sp5kIqCapabilityCfgSet(sp5kIqCapability_t sel, ...);

/*#endif */

UINT32 sp5kCdspLdcCoordinateTransfer( UINT32 x, UINT32 y, UINT32 boxSize, UINT32 * xTrans, UINT32 * yTrans, UINT32 * boxSizeTrans );
UINT32 sp5kCdspLdcCoordinateInvTransfer( UINT32 x, UINT32 y, UINT32 boxSize, UINT32 * xTrans, UINT32 * yTrans, UINT32 * boxSizeTrans );
void sp5kIqCfgColorDistillationCtrl(unsigned short nHueAng, unsigned short nConvg, unsigned short nConvg2, unsigned short nDistPercent ,unsigned char *pSatLut);

#endif /* _SP5K_CDSP_API_H_ */


