/**************************************************************************
 *
 *       Copyright (c) 2005-2012 by iCatch Technology, Inc.
 *
 *  This software is copyrighted by and is the property of iCatch
 *  Technology, Inc.. All rights are reserved by iCatch Technology, Inc..
 *  This software may only be used in accordance with the corresponding
 *  license agreement. Any unauthorized use, duplication, distribution,
 *  or disclosure of this software is expressly forbidden.
 *
 *  This Copyright notice MUST not be removed or modified without prior
 *  written consent of iCatch Technology, Inc..
 *
 *  iCatch Technology, Inc. reserves the right to modify this software
 *  without notice.
 *
 *  iCatch Technology, Inc.
 *  19-1, Innovation First Road, Science-Based Industrial Park,
 *  Hsin-Chu, Taiwan, R.O.C.
 *
 *  Author:
 *
 **************************************************************************/
#ifndef _SP5K_MEDIA_API_H_
#define _SP5K_MEDIA_API_H_

/**************************************************************************
 *                         H E A D E R   F I L E S
 **************************************************************************/
#include "middleware/common_types.h"
#include "middleware/media_def.h"

/**************************************************************************
 *                           C O N S T A N T S
 **************************************************************************/
/* general */
#define SP5K_MEDIA_DISABLE  0
#define SP5K_MEDIA_ENABLE   1

#define SP5K_MEDIA_MAX_FILE_NAME  MEDIA_MAX_FILE_NAME

/**
* [ media attribute ]
* \note
* 1. Any information which will be stored in media files and which can be parsed from media files directly.
* The word ¡§directly¡¨ means the information cannot be speculated from media files.
* 2. Elapsed time during record or playback
*/
#define SP5K_MEDIA_ATTR_FILE_NAME              MEDIA_ATTR_FILE_NAME
#define SP5K_MEDIA_ATTR_FILE_TYPE              MEDIA_ATTR_FILE_TYPE /*MEDIA_ATTR_FILE_NAME_BUF*/ /* modified by Edward 20070521 */
#define SP5K_MEDIA_ATTR_WIDTH                  MEDIA_ATTR_WIDTH
#define SP5K_MEDIA_ATTR_HEIGHT                 MEDIA_ATTR_HEIGHT
#define SP5K_MEDIA_ATTR_DURATION               MEDIA_ATTR_DURATION
#define SP5K_MEDIA_ATTR_ELAPSED_TIME           MEDIA_ATTR_ELAPSED_TIME
#define SP5K_MEDIA_ATTR_VIDEO_CODEC            MEDIA_ATTR_VIDEO_CODEC
#define SP5K_MEDIA_ATTR_VIDEO_BRC_TYPE         MEDIA_ATTR_VIDEO_BRC_TYPE
#define SP5K_MEDIA_ATTR_VIDEO_AVG_BITRATE      MEDIA_ATTR_VIDEO_AVG_BITRATE
#define SP5K_MEDIA_ATTR_VIDEO_FRAME_RATE       MEDIA_ATTR_VIDEO_FRAME_RATE
#define SP5K_MEDIA_ATTR_AUDIO_CODEC            MEDIA_ATTR_AUDIO_CODEC
#define SP5K_MEDIA_ATTR_AUDIO_BRC_TYPE         MEDIA_ATTR_AUDIO_BRC_TYPE
#define SP5K_MEDIA_ATTR_AUDIO_AVG_BITRATE      MEDIA_ATTR_AUDIO_AVG_BITRATE
#define SP5K_MEDIA_ATTR_AUDIO_SAMPLE_RATE      MEDIA_ATTR_AUDIO_SAMPLE_RATE
#define SP5K_MEDIA_ATTR_AUDIO_SAMPLE_BITS      MEDIA_ATTR_AUDIO_SAMPLE_BITS
#define SP5K_MEDIA_ATTR_AUDIO_CHANNELS         MEDIA_ATTR_AUDIO_CHANNELS
#define SP5K_MEDIA_ATTR_AUDIO_BLOCK_ALIGN 	   MEDIA_ATTR_AUDIO_BLOCK_ALIGN
#define SP5K_MEDIA_ATTR_SEEKABLE               MEDIA_ATTR_SEEKABLE
#define SP5K_MEDIA_ATTR_SUBTITLE_OPTION        MEDIA_ATTR_WITH_SUBTITLE
#define SP5K_MEDIA_ATTR_MJPG_INITIAL_Q_FACTOR  MEDIA_ATTR_MJPG_INITIAL_Q_FACTOR	/* 2015/12/11: it will be replaced by SP5K_MEDIA_ATTR_INIT_QVALUE */
#define SP5K_MEDIA_ATTR_INIT_QVALUE            MEDIA_ATTR_INIT_QVALUE
#define SP5K_MEDIA_ATTR_CUR_QVALUE             MEDIA_ATTR_CUR_QVALUE
#define SP5K_MEDIA_ATTR_REC_TAGS               MEDIA_ATTR_REC_TAGS
#define SP5K_MEDIA_ATTR_USER_DATA_SIZE         MEDIA_ATTR_USER_DATA_SIZE
#define SP5K_MEDIA_ATTR_USER_DATA              MEDIA_ATTR_USER_DATA
#define SP5K_MEDIA_ATTR_YUV_FORMAT             MEDIA_ATTR_YUV_FORMAT
#define SP5K_MEDIA_ATTR_IDENTIFY_TAGS          MEDIA_ATTR_IDENTIFY_TAGS

#define SP5K_MEDIA_ATTR_H264_ENTROPY_MODE      MEDIA_ATTR_H264_ENTROPY_MODE
#define SP5K_MEDIA_ATTR_H264_GOP_STRUCTURE     MEDIA_ATTR_H264_GOP_STRUCTURE
#define SP5K_MEDIA_ATTR_H264_GOP_NO            MEDIA_ATTR_H264_GOP_NO
#define SP5K_MEDIA_ATTR_H264_QP                MEDIA_ATTR_H264_QP
#define SP5K_MEDIA_ATTR_H264_QP_I              MEDIA_ATTR_H264_QP_I
#define SP5K_MEDIA_ATTR_H264_PROFILE           MEDIA_ATTR_H264_PROFILE
#define SP5K_MEDIA_ATTR_H264_INTRA_MODE        MEDIA_ATTR_H264_INTRA_MODE
#define SP5K_MEDIA_ATTR_H264_INTERLACE         MEDIA_ATTR_H264_INTERLACE
#define SP5K_MEDIA_ATTR_H264_SLICE_NO          MEDIA_ATTR_H264_SLICE_NO
#define SP5K_MEDIA_ATTR_H264_VUI_TAG           MEDIA_ATTR_H264_VUI_TAG
#define SP5K_MEDIA_ATTR_H264_IDR_INTERVAL      MEDIA_ATTR_H264_IDR_INTERVAL
#define SP5K_MEDIA_ATTR_H264_AUD_SEI_INFO      MEDIA_ATTR_H264_AUD_SEI_INFO
#define SP5K_MEDIA_ATTR_H264_COLOR_PARAM       MEDIA_ATTR_H264_COLOR_PARAM
#define SP5K_MEDIA_ATTR_H264_SPS_PPS_SIZE      MEDIA_ATTR_H264_SPS_PPS_SIZE
#define SP5K_MEDIA_ATTR_H264_SPS_PPS_DATA      MEDIA_ATTR_H264_SPS_PPS_DATA
#define SP5K_MEDIA_ATTR_H264_RC_MOTIONLESS           MEDIA_ATTR_H264_MOTIONLESS

#define SP5K_MEDIA_ATTR_2ND_WIDTH              MEDIA_ATTR_2ND_WIDTH
#define SP5K_MEDIA_ATTR_2ND_HEIGHT             MEDIA_ATTR_2ND_HEIGHT
#define SP5K_MEDIA_ATTR_2ND_VIDEO_CODEC        MEDIA_ATTR_2ND_VIDEO_CODEC
#define SP5K_MEDIA_ATTR_2ND_VIDEO_BRC_TYPE     MEDIA_ATTR_2ND_VIDEO_BRC_TYPE
#define SP5K_MEDIA_ATTR_2ND_VIDEO_AVG_BITRATE  MEDIA_ATTR_2ND_VIDEO_AVG_BITRATE
#define SP5K_MEDIA_ATTR_2ND_VIDEO_FRAME_RATE   MEDIA_ATTR_2ND_VIDEO_FRAME_RATE
#define SP5K_MEDIA_ATTR_2ND_ELAPSED_TIME       MEDIA_ATTR_2ND_ELAPSED_TIME

#define SP5K_MEDIA_ATTR_2ND_H264_ENTROPY_MODE  MEDIA_ATTR_2ND_H264_ENTROPY_MODE
#define SP5K_MEDIA_ATTR_2ND_H264_GOP_STRUCTURE MEDIA_ATTR_2ND_H264_GOP_STRUCTURE
#define SP5K_MEDIA_ATTR_2ND_H264_GOP_NO        MEDIA_ATTR_2ND_H264_GOP_NO
#define SP5K_MEDIA_ATTR_2ND_H264_QP            MEDIA_ATTR_2ND_H264_QP
#define SP5K_MEDIA_ATTR_2ND_H264_QP_I          MEDIA_ATTR_2ND_H264_QP_I
#define SP5K_MEDIA_ATTR_2ND_H264_PROFILE       MEDIA_ATTR_2ND_H264_PROFILE
#define SP5K_MEDIA_ATTR_2ND_H264_INTERLACE     MEDIA_ATTR_2ND_H264_INTERLACE
#define SP5K_MEDIA_ATTR_2ND_H264_SLICE_NO      MEDIA_ATTR_2ND_H264_SLICE_NO
#define SP5K_MEDIA_ATTR_2ND_H264_IDR_INTERVAL  MEDIA_ATTR_2ND_H264_IDR_INTERVAL

#define SP5K_MEDIA_ATTR_MERGE_DST_FILE         MEDIA_ATTR_MERGE_DST_FILE
#define SP5K_MEDIA_ATTR_MERGE_DST_AUD_CODEC    MEDIA_ATTR_MERGE_DST_AUD_CODEC
#define SP5K_MEDIA_ATTR_SW_TRIGGER_DST_FILE    MEDIA_ATTR_SW_TRIGGER_DST_FILE
#define SP5K_MEDIA_ATTR_TRIM_DST_FILE          MEDIA_ATTR_TRIM_DST_FILE

#define SP5K_MEDIA_ATTR_VIDEO_MAX_BITRATE		MEDIA_ATTR_VIDEO_MAX_BITRATE
#define SP5K_MEDIA_ATTR_VIDEO_MIN_BITRATE		MEDIA_ATTR_VIDEO_MIN_BITRATE
#define SP5K_MEDIA_ATTR_2ND_VIDEO_MAX_BITRATE	MEDIA_ATTR_2ND_VIDEO_MAX_BITRATE
#define SP5K_MEDIA_ATTR_2ND_VIDEO_MIN_BITRATE	MEDIA_ATTR_2ND_VIDEO_MIN_BITRATE

#define SP5K_MEDIA_ATTR_REC_STATE_VIDEO_FIFO_USED MEDIA_ATTR_REC_STATE_VIDEO_FIFO_USED
#define SP5K_MEDIA_ATTR_REC_STATE_AUDIO_FIFO_USED MEDIA_ATTR_REC_STATE_AUDIO_FIFO_USED

#define SP5K_MEDIA_ATTR_SPHERICAL_VIDEO_TAG_ENABLE MEDIA_ATTR_SPHERICAL_VIDEO_TAG_ENABLE
#define SP5K_MEDIA_ATTR_VIDEO_VARIABLE_DURATION_EN MEDIA_ATTR_VIDEO_VARIABLE_DURATION_EN

#define SP5K_MEDIA_UBR                         MEDIA_UBR
#define SP5K_MEDIA_CBR                         MEDIA_CBR
#define SP5K_MEDIA_VBR                         MEDIA_VBR

#define SP5K_MEDIA_H264_GOP_IBBP               MEDIA_H264_GOP_IBBP
#define SP5K_MEDIA_H264_GOP_IPPP               MEDIA_H264_GOP_IPPP
#define SP5K_MEDIA_H264_GOP_IIII               MEDIA_H264_GOP_IIII

#define SP5K_MEDIA_H264_ENTROPY_CABAC          MEDIA_H264_ENTROPY_CABAC
#define SP5K_MEDIA_H264_ENTROPY_CAVLC          MEDIA_H264_ENTROPY_CAVLC

#define SP5K_MEDIA_H264_PROFILE_BASE_MAIN      MEDIA_H264_PROFILE_BASE_MAIN
#define SP5K_MEDIA_H264_PROFILE_HIGH           MEDIA_H264_PROFILE_HIGH

#define SP5K_MEDIA_H264_INTRA_4_16             MEDIA_H264_INTRA_4_16
#define SP5K_MEDIA_H264_INTRA_8_16             MEDIA_H264_INTRA_8_16
#define SP5K_MEDIA_H264_INTRA_4_8              MEDIA_H264_INTRA_4_8

#define SP5K_MEDIA_H264_VUI_VIDEO_SIGNAL_TYPE     MEDIA_H264_VUI_VIDEO_SIGNAL_TYPE
#define SP5K_MEDIA_H264_VUI_ASPECT_RATIO_INFO     MEDIA_H264_VUI_ASPECT_RATIO_INFO
#define SP5K_MEDIA_H264_VUI_OVERSCAN_INFO         MEDIA_H264_VUI_OVERSCAN_INFO
#define SP5K_MEDIA_H264_VUI_CHROMA_LOC_INFO       MEDIA_H264_VUI_CHROMA_LOC_INFO
#define SP5K_MEDIA_H264_VUI_TIMING_INFO           MEDIA_H264_VUI_TIMING_INFO
#define SP5K_MEDIA_H264_VUI_NAL_HRD_PARAMETERS    MEDIA_H264_VUI_NAL_HRD_PARAMETERS
#define SP5K_MEDIA_H264_VUI_VCL_HRD_PARAMETERS    MEDIA_H264_VUI_VCL_HRD_PARAMETERS
#define SP5K_MEDIA_H264_VUI_PIC_STRUCT            MEDIA_H264_VUI_PIC_STRUCT
#define SP5K_MEDIA_H264_VUI_BITSTREAM_RESTRICTION MEDIA_H264_VUI_BITSTREAM_RESTRICTION


#define SP5K_MEDIA_H264_SEI_CB_STATUS_ADD_TO_STREAM			(1<<0)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_UPD_CALLBACK	(1<<1)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_STREAM_ID_0		(1<<2)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_STREAM_ID_1		(1<<3)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_SLICE_P	 		(1<<4)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_SLICE_B	 		(1<<5)
#define SP5K_MEDIA_H264_SEI_CB_STATUS_BLOCK_SLICE_I			(1<<6)


#if 1 /* obsolete */
#define SP5K_MEDIA_GOP_IBBP                    MEDIA_H264_GOP_IBBP
#define SP5K_MEDIA_GOP_IPPP                    MEDIA_H264_GOP_IPPP
#define SP5K_MEDIA_GOP_IIII                    MEDIA_H264_GOP_IIII

#define SP5K_MEDIA_PROFILE_BASE_MAIN           MEDIA_H264_PROFILE_BASE_MAIN
#define SP5K_MEDIA_PROFILE_HIGH                MEDIA_H264_PROFILE_HIGH

#define SP5K_MEDIA_INTRA_4_16                  MEDIA_H264_INTRA_4_16
#define SP5K_MEDIA_INTRA_8_16                  MEDIA_H264_INTRA_8_16
#define SP5K_MEDIA_INTRA_4_8                   MEDIA_H264_INTRA_4_8
#endif

#define SP5K_MEDIA_WAV  SP5K_DCF_FILETYPE_WAV
#define SP5K_MEDIA_MP3  SP5K_DCF_FILETYPE_MP3
#define SP5K_MEDIA_AVI  SP5K_DCF_FILETYPE_AVI
#define SP5K_MEDIA_ASF  SP5K_DCF_FILETYPE_ASF
#define SP5K_MEDIA_WMA  SP5K_DCF_FILETYPE_WMA
#define SP5K_MEDIA_AAC  SP5K_DCF_FILETYPE_AAC
#define SP5K_MEDIA_MOV	SP5K_DCF_FILETYPE_MOV
#define SP5K_MEDIA_MP4  SP5K_DCF_FILETYPE_MP4
#define SP5K_MEDIA_MTS  SP5K_EXDCF_FILETYPE_MTS
#define SP5K_MEDIA_TS   SP5K_EXDCF_FILETYPE_MTS


#define SP5K_MEDIA_AUDIO_UNKNOWN     MEDIA_AUDIO_UNKNOWN
#define SP5K_MEDIA_AUDIO_PCM         MEDIA_AUDIO_PCM
/*#define SP5K_MEDIA_AUDIO_ADPCM       MEDIA_AUDIO_ADPCM*/
#define SP5K_MEDIA_AUDIO_ALAW        MEDIA_AUDIO_ALAW
#define SP5K_MEDIA_AUDIO_MULAW       MEDIA_AUDIO_MULAW
#define SP5K_MEDIA_AUDIO_IMA_ADPCM   MEDIA_AUDIO_IMA_ADPCM
#define SP5K_MEDIA_AUDIO_MPEGLAYER3  MEDIA_AUDIO_MPEGLAYER3
#define SP5K_MEDIA_AUDIO_WMA1        MEDIA_AUDIO_WMA1
#define SP5K_MEDIA_AUDIO_AAC         MEDIA_AUDIO_AAC

#define SP5K_MEDIA_VIDEO_UNKNOWN  MEDIA_VIDEO_UNKNOWN
#define SP5K_MEDIA_VIDEO_MPEG4    MEDIA_VIDEO_MPEG4
#define SP5K_MEDIA_VIDEO_MJPG     MEDIA_VIDEO_MJPG
#define SP5K_MEDIA_VIDEO_H264     MEDIA_VIDEO_H264
#define SP5K_MEDIA_VIDEO_CUSTOM   MEDIA_VIDEO_CUSTOM

/**
* [ media configuration ]
* \note
* All other information which cannot be retrieved from media files directly.
*/

/* media common configuration */
#define SP5K_MEDIA_AVI_INTERLEAVE_INTERVAL      MEDIA_AVI_INTERLEAVE_INTERVAL


/* media record configuration */
#define SP5K_MEDIA_REC_FLIP_ROTATE            MEDIA_REC_FLIP_ROTATE
#define SP5K_MEDIA_REC_ALC                    MEDIA_REC_ALC
#define SP5K_MEDIA_REC_ALC_MODE               MEDIA_REC_ALC_MODE
#define SP5K_MEDIA_REC_DIS_LEVEL              MEDIA_REC_DIS_LEVEL
#define SP5K_MEDIA_REC_PAUSE_CALLBACK         MEDIA_REC_PAUSE_CALLBACK
#define SP5K_MEDIA_REC_DISK_THR_KB            MEDIA_REC_DISK_THR_KB
#define SP5K_MEDIA_REC_SEAMLESS_CALLBACK      MEDIA_REC_SEAMLESS_CALLBACK
#define SP5K_MEDIA_REC_FILENAME_CALLBACK	  MEDIA_REC_FILENAME_CALLBACK
#define SP5K_MEDIA_REC_FILE_CLOSE_CALLBACK    MEDIA_REC_FILE_CLOSE_CALLBACK
#define SP5K_MEDIA_REC_FILE_CHANGED_CALLBACK  MEDIA_REC_FILE_CHANGED_CALLBACK
#define SP5K_MEDIA_REC_USRDATA_CALLBACK       MEDIA_REC_USRDATA_CALLBACK
#define SP5K_MEDIA_REC_VLC_BUF_SIZE           MEDIA_REC_VLC_BUF_SIZE
#define SP5K_MEDIA_REC_VLC_BUF_CNT            MEDIA_REC_VLC_BUF_CNT
#define SP5K_MEDIA_REC_2ND_VLC_BUF_CNT        MEDIA_REC_2ND_VLC_BUF_CNT
#define SP5K_MEDIA_REC_2ND_VLC_BUF_SIZE       MEDIA_REC_2ND_VLC_BUF_SIZE
#define SP5K_MEDIA_REC_MAX_QVALUE             MEDIA_REC_MAX_QVALUE
#define SP5K_MEDIA_REC_MIN_QVALUE             MEDIA_REC_MIN_QVALUE
#define SP5K_MEDIA_REC_MJPG_Q_TABLE_Y         MEDIA_REC_MJPG_Q_TABLE_Y
#define SP5K_MEDIA_REC_MJPG_Q_TABLE_UV        MEDIA_REC_MJPG_Q_TABLE_UV
#define SP5K_MEDIA_REC_DUP_L_TO_R_ENABLE      MEDIA_REC_DUP_L_TO_R_ENABLE
#define SP5K_MEDIA_REC_LR_SWAP_ENABLE         MEDIA_REC_LR_SWAP_ENABLE
#define SP5K_MEDIA_REC_AUD_FILTERMUX          MEDIA_REC_AUD_FILTERMUX
#define SP5K_MEDIA_REC_DIS_COMP_BYPASS        MEDIA_REC_DIS_COMP_BYPASS /**< Bypass DIS compenstation: 0=bypass, 1=normal flow (default) */
#define SP5K_MEDIA_REC_DIS_COMP_TYPE          MEDIA_REC_DIS_COMP_TYPE /**< DIS compenstation Type: 0=fast(default), 1=smooth, 2=not support, 3=customer cb */
#define SP5K_MEDIA_REC_DIS_COMP_FAST          0x0
#define SP5K_MEDIA_REC_DIS_COMP_SMOOTH        0x1
#define SP5K_MEDIA_REC_DIS_COMP_SMOOTH_RSC    0x2
#define SP5K_MEDIA_REC_DIS_COMP_CUSTOMER_CB   0x3

#define SP5K_MEDIA_REC_H264_PFRAME_SKIP       MEDIA_REC_H264_PFRAME_SKIP
#define SP5K_MEDIA_REC_H264_SEI_CB_INIT_CB       MEDIA_REC_H264_SEI_CB_INIT_CB
#define SP5K_MEDIA_REC_AUD_FRAME_DURATION     MEDIA_REC_AUD_FRAME_DURATION


/*
 * DIS gmv calculate customer callback
 */
#define SP5K_MEDIA_REC_DIS_GMV_CALC_CB       MEDIA_REC_DIS_GMV_CALC_CB

/*
 * DIS compenstation Type: 3, compensate offset calculate customer cb
 */
#define SP5K_MEDIA_REC_DIS_COMPENSATE_CALC_CB       MEDIA_REC_DIS_COMPENSATE_CALC_CB

/*
 * DIS compensation range in %, this defines the available compensate region.
 * the SP5K_MEDIA_REC_DIS_COMP_RANGE_WIDTH is limited by this and the
 * SP5K_MEDIA_REC_DIS_COMP_RANGE_MAX_W.
 */
#define SP5K_MEDIA_REC_DIS_COMP_RANGE         MEDIA_REC_DIS_COMP_RANGE
#define SP5K_MEDIA_REC_DIS_COMP_RANGE_MAX_W   MEDIA_REC_DIS_COMP_RANGE_MAX_W /* DIS compensation range max in pixel*/
#define SP5K_MEDIA_REC_DIS_COMP_RANGE_MAX_H   MEDIA_REC_DIS_COMP_RANGE_MAX_H /* DIS compensation range max in pixel*/
#define SP5K_MEDIA_REC_DIS_COMP_RANGE_WIDTH   MEDIA_REC_DIS_COMP_RANGE_WIDTH /**< DIS compensation range in pixel*/
#define SP5K_MEDIA_REC_DIS_COMP_RANGE_HEIGHT  MEDIA_REC_DIS_COMP_RANGE_HEIGHT /**< DIS compensation range in pixel*/
#define SP5K_MEDIA_REC_DIS_EDGE_THRESHOLD     MEDIA_REC_DIS_EDGE_THRESHOLD
#define SP5K_MEDIA_REC_PIV_CONFIG             MEDIA_REC_PIV_CONFIG
#define SP5K_MEDIA_REC_PIV_AVAILABLE_JOB      MEDIA_REC_PIV_AVAILABLE_JOB
#define SP5K_MEDIA_REC_PIV_FRAMES             MEDIA_REC_PIV_FRAMES
#define SP5K_MEDIA_REC_PIV_FRAMES_WIDTH       MEDIA_REC_PIV_FRAMES_WIDTH
#define SP5K_MEDIA_REC_PIV_FRAMES_HEIGHT      MEDIA_REC_PIV_FRAMES_HEIGHT
#define SP5K_MEDIA_REC_RECOVERY_EN		  	  MEDIA_REC_RECOVERY_EN
#define SP5K_MEDIA_REC_RECOVERY_OVER4G_EN	  MEDIA_REC_RECOVERY_OVER4G_EN
#define SP5K_MEDIA_REC_RECOVERY_FLUSH_INTERVAL MEDIA_REC_RECOVERY_FLUSH_INTERVAL
#define SP5K_MEDIA_REC_EVENT_TRIGGER_EN	   	  MEDIA_REC_EVENT_TRIGER_EN
#define SP5K_MEDIA_REC_TRIGGER_TIME_SLOT	  MEDIA_REC_TRIGGER_TIME_SLOT
#define SP5K_MEDIA_REC_TRIGGER_FRONT_TIME	  MEDIA_REC_TRIGGER_FRONT_TIME
#define SP5K_MEDIA_REC_TRIGGER_BEHIND_TIME	  MEDIA_REC_TRIGGER_BEHIND_TIME
#define SP5K_MEDIA_REC_EVENT_TRIGGER_MODE	  MEDIA_REC_EVENT_TRIGGER_MODE
#define SP5K_MEDIA_REC_TRIGGER_FILE_NAME      MEDIA_REC_TRIGGER_FILE_NAME
#define SP5K_MEDIA_REC_2ND_TRIGGER_FILE_NAME  MEDIA_REC_2ND_TRIGGER_FILE_NAME
#define SP5K_MEDIA_REC_EVENT_TRIGGER_TYPE	  MEDIA_REC_EVENT_TRIGGER_TYPE
#define SP5K_MEDIA_REC_INTERRUPT_SEAMLESS	  MEDIA_REC_INTERRUPT_SEAMLESS
#define SP5K_MEDIA_REC_UNINTERRUPT_SEAMLESS	  MEDIA_REC_UNINTERRUPT_SEAMLESS
#define SP5K_MEDIA_REC_PERIODIC_SYNC_EN  MEDIA_REC_PERIODIC_SYNC_EN
#define SP5K_MEDIA_REC_PERIODIC_SYNC_CALLBACK_SET  MEDIA_REC_PERIODIC_SYNC_CALLBACK_SET
#define SP5K_MEDIA_REC_EXTENSION_TYPE_EN     MEDIA_REC_EXTENSION_TYPE_EN



/*
 * SP5K_MEDIA_REC_PIV_MODE0:
 *   UINT32 frmCb(UINT32 id, UINT32 addr, sp5kYuvCbImgSize_t *p, void *rsv);
 * SP5K_MEDIA_REC_PIV_MODE1/SP5K_MEDIA_REC_PIV_MODE2_OPTx:
 *   UINT32 frmCb(UINT32 id, UINT32 addr, sp5kImgWbInfo_t *p, void *rsv);
 */
#define SP5K_MEDIA_REC_PIV_FRAME_CB           MEDIA_REC_PIV_FRAME_CB
/*
 * UINT32 procCb(UINT32 id, UINT32 addr, sp5kYuvCbImgSize_t *p, void *rsv);
 * return TRUE(1) for save file.
 */
#define SP5K_MEDIA_REC_PIV_PROC_CB            MEDIA_REC_PIV_PROC_CB
/*
 * UINT32 iqCb(UINT32 param1, UINT32 param2, void *param3);
*/
#define SP5K_MEDIA_REC_PIV_IQ_CB           	  MEDIA_REC_PIV_IQ_CB
/* backward compatible */
#define SP5K_MEDIA_REC_CAPTURE_FRAMES         MEDIA_REC_PIV_FRAMES
#define SP5K_MEDIA_REC_CAPTURE_FRAME_CB       MEDIA_REC_PIV_FRAME_CB
#define SP5K_MEDIA_REC_CAPTURE_PROC_CB        MEDIA_REC_PIV_PROC_CB
#define SP5K_MEDIA_REC_CAPTURE_IQ_CB       	  MEDIA_REC_PIV_IQ_CB

#define SP5K_MEDIA_REC_INPUT_FRAME_RATE       MEDIA_REC_INPUT_FRAME_RATE
#define SP5K_MEDIA_REC_2ND_INPUT_FRAME_RATE   MEDIA_REC_2ND_INPUT_FRAME_RATE
#if REC_FRAME_RATE_SWITCH_SUPPORT
#define SP5K_MEDIA_REC_FRAME_RATE_SWITCH_EN   MEDIA_REC_FRAME_RATE_SWITCH_EN
#endif
#if REC_AUDIO_RESAMPLE
#define SP5K_MEDIA_REC_AUDIO_RESAMPLE_EN      MEDIA_REC_AUDIO_RESAMPLE_EN
#endif
#if REC_IFRAME_SUPPORT
#define SP5K_MEDIA_REC_IFRAME_MODE_ENABLE     MEDIA_REC_IFRAME_MODE_ENABLE
#endif
#define SP5K_MEDIA_REC_VIDEO_FIFO_BUF_NO      MEDIA_REC_VIDEO_FIFO_BUF_NO
#define SP5K_MEDIA_REC_AUDIO_FIFO_BUF_NO      MEDIA_REC_AUDIO_FIFO_BUF_NO

/*
 * UINT32 swtrigCb(UINT8 *pbuf, sp5kYuvCbImgSize_t *p, UINT32 rsvd0, UINT32 rsvd1)
 * return SUCCESS to trigger the codec.
 */
#define SP5K_MEDIA_REC_SWTRIG_CB              MEDIA_REC_SWTRIG_CB
#define SP5K_MEDIA_REC_SWTRIG_CFG_PTR_CB      MEDIA_REC_SWTRIG_CFG_PTR_CB
#define SP5K_MEDIA_REC_SEAMLESS_TIME_SLOT     MEDIA_REC_SEAMLESS_TIME_SLOT
#define SP5K_MEDIA_REC_SEAMLESS_SIZE_SLOT     MEDIA_REC_SEAMLESS_SIZE_SLOT
#define SP5K_MEDIA_REC_SEAMLESS_FULL_OPTION   MEDIA_REC_SEAMLESS_FULL_OPTION
#define SP5K_MEDIA_REC_MULTI_STREAM_EN        MEDIA_REC_MULTI_STREAM_EN
#define SP5K_MEDIA_REC_MULTI_STREAMS          MEDIA_REC_MULTI_STREAMS
#define SP5K_MEDIA_REC_SEAMLESS_SIZE_LIMIT_CB	MEDIA_REC_SEAMLESS_SIZE_LIMIT_CB
#define SP5K_MEDIA_REC_SEAMLESS_CHANGE_FILE  	  MEDIA_REC_SEAMLESS_CHANGE_FILE
#define SP5K_MEDIA_REC_VIDEO_STREAM_ORDER     MEDIA_REC_VIDEO_STREAM_ORDER
#define SP5K_MEDIA_REC_H264_STOP_MODE     	  MEDIA_REC_H264_STOP_MODE
#define SP5K_MEDIA_REC_H264_IFRAME_SHIELD_EN  MEDIA_REC_H264_IFRAME_SHIELD_EN
#define SP5K_MEDIA_REC_H264_CLK               MEDIA_REC_H264_CLK


/*For SP5K_MEDIA_REC_SEAMLESS_FULL_OPTION*/
#define SP5K_MEDIA_REC_SEAMLESS_FULL_OPT_DELETE_OLDEST        0
#define SP5K_MEDIA_REC_SEAMLESS_FULL_OPT_STOP                 1

#define SP5K_MEDIA_REC_OFF  0
#define SP5K_MEDIA_REC_ON   1

#define SP5K_MEDIA_REC_ROTATE_0         MEDIA_REC_ROTATE_0
#define SP5K_MEDIA_REC_ROTATE_90        MEDIA_REC_ROTATE_90
#define SP5K_MEDIA_REC_ROTATE_180       MEDIA_REC_ROTATE_180
#define SP5K_MEDIA_REC_ROTATE_270       MEDIA_REC_ROTATE_270
#define SP5K_MEDIA_REC_FLIP_VERTICAL    MEDIA_REC_FLIP_VERTICAL
#define SP5K_MEDIA_REC_FLIP_HORIZONTAL  MEDIA_REC_FLIP_HORIZONTAL

#define SP5K_MEDIA_REC_YUV422  MEDIA_REC_YUV422
#define SP5K_MEDIA_REC_YUV420  MEDIA_REC_YUV420

#define SP5K_MEDIA_REC_DIS_REC_ONLY     MEDIA_REC_DIS_REC_ONLY
#define SP5K_MEDIA_REC_DIS_REC_PV       MEDIA_REC_DIS_REC_PV

#define SP5K_MEDIA_REC_IS_TYPE          MEDIA_REC_DIS_LEVEL
#define SP5K_MEDIA_REC_IS_OFF           MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_IS_DIS           SP5K_MEDIA_REC_DIS_REC_ONLY
#define SP5K_MEDIA_REC_IS_RSC           MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_IS_DIS_RSC       MEDIA_REC_DIS_OFF

/** The following definition are obsolete and will be removed sometime later */
#define SP5K_MEDIA_REC_DIS_OFF          MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_DIS_LOW          MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_DIS_MID          MEDIA_REC_DIS_MID
#define SP5K_MEDIA_REC_DIS_HIGH         MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_DIS_EDGE_WIN_H_COUNT		MEDIA_REC_DIS_EDGE_WIN_H_COUNT
#define SP5K_MEDIA_REC_DIS_EDGE_WIN_V_COUNT		MEDIA_REC_DIS_EDGE_WIN_V_COUNT
#define SP5K_MEDIA_REC_RSC_OFF          MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_LOW          MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_MID          MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_HIGH         MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_DIS_OFF      MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_DIS_LOW      MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_DIS_MID      MEDIA_REC_DIS_OFF
#define SP5K_MEDIA_REC_RSC_DIS_HIGH     MEDIA_REC_DIS_OFF

/** For SP5K_MEDIA_REC_H264_STOP_MODE  */
#define SP5K_MEDIA_REC_H264_NORMAL_STOP MEDIA_REC_H264_NORMAL_STOP
#define SP5K_MEDIA_REC_H264_FAST_STOP   MEDIA_REC_H264_FAST_STOP


/* media record control */
#define SP5K_MEDIA_REC_PAUSE              MEDIA_REC_PAUSE
#define SP5K_MEDIA_REC_RESUME             MEDIA_REC_RESUME
#define SP5K_MEDIA_REC_PIV_CAPTURE        MEDIA_REC_PIV_CAPTURE
#define SP5K_MEDIA_REC_FRAME_CAPTURE      MEDIA_REC_PIV_CAPTURE
#define SP5K_MEDIA_REC_JFIF_CAPTURE       MEDIA_REC_JFIF_CAPTURE
#define SP5K_MEDIA_REC_EXIF_CAPTURE       MEDIA_REC_EXIF_CAPTURE
#define SP5K_MEDIA_REC_SWTRIG_START       MEDIA_REC_SWTRIG_START
#define SP5K_MEDIA_REC_SWTRIG_STOP        MEDIA_REC_SWTRIG_STOP
#define SP5K_MEDIA_REC_PREREC_MS          MEDIA_REC_PREREC_MS
#define SP5K_MEDIA_REC_PREREC_INIT		  MEDIA_REC_PREREC_INIT
#define SP5K_MEDIA_REC_PREREC_CTRL		  MEDIA_REC_PREREC_CTRL
#define SP5K_MEDIA_REC_APPEND_NEXT_VIDEO  MEDIA_REC_APPEND_NEXT_VIDEO
#define SP5K_MEDIA_REC_END_CLIP_MS        MEDIA_REC_END_CLIP_MS
#define SP5K_MEDIA_REC_START_CLIP_MS      MEDIA_REC_START_CLIP_MS

/*
 * Pointer to the callbacks for custom stream controller.
 * (sp5kMediaRecScCustomCbList_t), should not be local variable.
 */
#define SP5K_MEDIA_REC_SC_CUSTOM_CBLIST   MEDIA_REC_SC_CUSTOM_CBLIST

/*
 * video and audio data chunk align flow
 */
#define SP5K_MEDIA_REC_DATA_CHUNK_ALIGN_FLOW      MEDIA_REC_DATA_CHUNK_ALIGN_FLOW

/* PIV Configuration */
#define SP5K_MEDIA_REC_PIV_MODE0          MEDIA_REC_PIV_MODE0
#define SP5K_MEDIA_REC_PIV_MODE1          MEDIA_REC_PIV_MODE1
#define SP5K_MEDIA_REC_PIV_MODE2_OPT1     MEDIA_REC_PIV_MODE2_OPT1
#define SP5K_MEDIA_REC_PIV_MODE2_OPT2     MEDIA_REC_PIV_MODE2_OPT2

/* Multiple Stream Programming */
/* SC = StreamController */
#define SP5K_MEDIA_REC_SC_CREATE          MEDIA_REC_SC_CREATE
#define SP5K_MEDIA_REC_SC_CREATE_EX       MEDIA_REC_SC_CREATE_EX
#define SP5K_MEDIA_REC_SC_DESTROY         MEDIA_REC_SC_DESTROY
#define SP5K_MEDIA_REC_SC_ATTACH          MEDIA_REC_SC_ATTACH
#define SP5K_MEDIA_REC_SC_DETACH          MEDIA_REC_SC_DETACH
#if REC_FRAME_RATE_SWITCH_SUPPORT
#define SP5k_MEDIA_REC_FRAME_RATE_SWITCH  MEDIA_REC_FRAME_RATE_SWITCH
#endif
#define SP5K_MEDIA_REC_STREAM_START       MEDIA_REC_STREAM_START
#define SP5K_MEDIA_REC_STREAM_STOP        MEDIA_REC_STREAM_STOP
#define SP5K_MEDIA_REC_STREAM_RESTART     MEDIA_REC_STREAM_RESTART

#define SP5K_MEDIA_REC_GET_STREAM_INFO    MEDIA_REC_GET_STREAM_INFO
#define SP5K_MEDIA_REC_GET_SC_INFO        MEDIA_REC_GET_SC_INFO

#define SP5K_MEDIA_REC_STREAM_NUM         MEDIA_REC_STREAM_NUM
#define SP5K_MEDIA_REC_STREAMS_ALL        MEDIA_REC_STREAMS_ALL
#define SP5K_MEDIA_REC_STREAM_1ST         MEDIA_REC_STREAM_1ST
#define SP5K_MEDIA_REC_STREAM_2ND         MEDIA_REC_STREAM_2ND
#define SP5K_MEDIA_REC_STREAM_3RD         MEDIA_REC_STREAM_3RD

#define SP5K_MEDIA_PLAY_STREAM_1ST        MEDIA_PLAY_STREAM_1ST
#define SP5K_MEDIA_PLAY_STREAM_2ND        MEDIA_PLAY_STREAM_2ND


/* Stream-Controller number */
#define SP5K_MEDIA_REC_SC_NUM_MAX         MEDIA_REC_SC_NUM_MAX
#define SP5K_MEDIA_REC_SC_TYPE_FILE       MEDIA_REC_SC_TYPE_FILE
#define SP5K_MEDIA_REC_SC_TYPE_RTP        MEDIA_REC_SC_TYPE_RTP
#define SP5K_MEDIA_REC_SC_TYPE_CUSTOM     MEDIA_REC_SC_TYPE_CUSTOM
#define SP5K_MEDIA_REC_SC_TYPE_ES         MEDIA_REC_SC_TYPE_ES
#define SP5K_MEDIA_REC_SC_TYPE_TS         MEDIA_REC_SC_TYPE_TS
#define SP5K_MEDIA_REC_SC_TYPE_UVC        MEDIA_REC_SC_TYPE_UVC
#define SP5K_MEDIA_REC_SC_TYPE_FRAMEWORK  MEDIA_REC_SC_TYPE_FRAMEWORK
#define SP5K_MEDIA_REC_PREREC_TRIG_MODE	  MEDIA_REC_PREREC_TRIG_MODE
#define SP5K_MEDIA_REC_PREREC_NORMAL_MODE   MEDIA_REC_PREREC_NORMAL_MODE
#define SP5K_MEDIA_REC_PREREC_TRIG_FILE		MEDIA_REC_PREREC_TRIG_FILE
#define SP5K_MEDIA_REC_PREREC_CLOSE_FILE	MEDIA_REC_PREREC_CLOSE_FILE

#define SP5K_MEDIA_REC_VIDEO_VFRC_ENABLE			MEDIA_REC_VIDEO_VFRC_ENABLE
#define SP5K_MEDIA_REC_VIDEO_VFRC_ATTR			MEDIA_REC_VIDEO_VFRC_ATTR	
#define SP5K_MEDIA_REC_VIDEO_VFRC_BITRATE		MEDIA_REC_VIDEO_VFRC_BITRATE
#define SP5K_MEDIA_REC_2ND_VIDEO_VFRC_ATTR		MEDIA_REC_2ND_VIDEO_VFRC_ATTR	
#define SP5K_MEDIA_REC_2ND_VIDEO_VFRC_BITRATE	MEDIA_REC_2ND_VIDEO_VFRC_BITRATE

#define sp5kMediaRecScCustomCbList_t      mediaRecScCustomCbList_t
#define sp5kMediaVideoTagUserDataGet_t    mediaVideoTagUserDataGet_t
#define sp5kMediaVideoTagUserData_t       mediaVideoTagUserData_t
#define sp5kMediaVideoTags_t              mediaVideoTags_t
#define sp5kMediaRecScCustomAudBlkGotCbinfo_t	mediaRecScCustomAudBlkGotCbInfo_t
#define sp5kMediaPlayAudFrmDataCbinfo_t         mediaPlayAudFrmDataCbInfo_t

/* media playback configuration */
#define SP5K_MEDIA_PLAY_MUTE_VIDEO          MEDIA_PLAY_MUTE_VIDEO
#define SP5K_MEDIA_PLAY_MUTE_AUDIO          MEDIA_PLAY_MUTE_AUDIO
#define SP5K_MEDIA_PLAY_FLIP_ROTATE         MEDIA_PLAY_FLIP_ROTATE
#define SP5K_MEDIA_PLAY_VIDEO_FF_END_PAUSE  MEDIA_PLAY_VIDEO_FF_END_PAUSE
#define SP5K_MEDIA_PLAY_TARGET_FRAME_RATE   MEDIA_PLAY_TARGET_FRAME_RATE
#define SP5K_MEDIA_PLAY_DISP_FRAME_CB       MEDIA_PLAY_DISP_FRAME_CB
#define SP5K_MEDIA_PLAY_VIDEO_FRAME_CB      SP5K_MEDIA_PLAY_DISP_FRAME_CB
#define SP5K_MEDIA_PLAY_YUV_SCALE_OPT		MEDIA_PLAY_YUV_SCALE_OPT
#define SP5K_MEDIA_PLAY_SEAMLESS_FILENAME_CB MEDIA_PLAY_SEAMLESS_FILENAME_CB
/*
 * void videoDataCb(frameBufInfo_t *pframes, UINT32 nframes, UINT32 pts,
 *    UINT32 fmt);
 * where fmt: 0 - YUV422, 1 - YUV420
 */
#define SP5K_MEDIA_PLAY_VIDEO_DATA_CB       MEDIA_PLAY_VIDEO_DATA_CB
#define SP5K_MEDIA_PLAY_AUDIO_DATA_CB       MEDIA_PLAY_AUDIO_DATA_CB
#define SP5K_MEDIA_PLAY_VIDEO_FRAME_DATA_CB MEDIA_PLAY_VIDEO_FRAME_DATA_CB
#define SP5K_MEDIA_PLAY_AUDIO_FRAME_DATA_CB MEDIA_PLAY_AUDIO_FRAME_DATA_CB
#define SP5K_MEDIA_PLAY_START_TIME          MEDIA_PLAY_START_TIME
#define SP5K_MEDIA_PLAY_END_TIME            MEDIA_PLAY_END_TIME
#define SP5K_MEDIA_PLAY_BG_MUSIC_VOLUME     MEDIA_PLAY_BG_MUSIC_VOLUME
#define SP5K_MEDIA_PLAY_DISP_UPD_DIS  MEDIA_PLAY_DISP_UPD_DIS

/**
 * typedef UINT32 (*pmediaPlaySoundEffectCb_t)(UINT32 timeStamp, UINT8* pBuf, UINT32 sampleRate,
 *                             UINT32 channelCnt, UINT32 sampleCnt, UINT32 sampleSize);
 */
#define SP5K_MEDIA_PLAY_SOUND_EFFECT_CB     MEDIA_PLAY_SOUND_EFFECT_CB
#define SP5K_MEDIA_PLAY_SOUND_EFFECT_SRC    MEDIA_PLAY_SOUND_EFFECT_SRC
#define SP5K_MEDIA_PLAY_USER_DATA_BUF       MEDIA_PLAY_USER_DATA_BUF
#define SP5K_MEDIA_PLAY_USRDATA_CALLBACK    MEDIA_PLAY_USRDATA_CALLBACK
#define SP5K_MEDIA_PLAY_VIDEO_SPEED_CTRL_CB  MEDIA_PLAY_VIDEO_SPEED_CTRL_CB
#define SP5K_MEDIA_PLAY_ERROR_HANDLE_MODE   MEDIA_PLAY_ERROR_HANDLE_MODE
#define SP5K_MEDIA_PLAY_HEADER_BUF_SIZE     MEDIA_PLAY_HEADER_BUF_SIZE
#define SP5K_MEDIA_PLAY_AFFINE              MEDIA_PLAY_AFFINE
#define SP5K_MEDIA_PLAY_MAX_DEC_BUF_NUM     MEDIA_PLAY_MAX_DEC_BUF_NUM
#define SP5K_MEDIA_PLAY_YUV_SCALE_DIV       MEDIA_PLAY_YUV_SCALE_DIV
#define SP5K_MEDIA_PLAY_AUDIO_CH_MIX_EN     MEDIA_PLAY_AUDIO_CH_MIX_EN
#define SP5K_MEDIA_PLAY_FILE2_START_MERGE_TIME       MEDIA_PLAY_FILE2_START_MERGE_TIME
#define SP5K_MEDIA_PLAY_VIDEO_STREAM    MEDIA_PLAY_VIDEO_STREAM
#define SP5K_MEDIA_PLAY_DISP_FRAME_RATE    MEDIA_PLAY_DISP_FRAME_RATE
#define SP5K_MEDIA_PLAY_DATA_SOURCE    MEDIA_PLAY_DATA_SOURCE



#define SP5K_MEDIA_PLAY_SOUND_EFFECT_SRC_BG_MUSIC  MEDIA_PLAY_SOUND_EFFECT_SRC_BG_MUSIC
#define SP5K_MEDIA_PLAY_SOUND_EFFECT_SRC_VIDEO     MEDIA_PLAY_SOUND_EFFECT_SRC_VIDEO
#define SP5K_MEDIA_PLAY_SOUND_EFFECT_SRC_MERGED    MEDIA_PLAY_SOUND_EFFECT_SRC_MERGED

#define SP5K_MEDIA_PLAY_START          0
#define SP5K_MEDIA_PLAY_ABORT          1
#define SP5K_MEDIA_PLAY_PAUSE          2
#define SP5K_MEDIA_PLAY_RESUME         3
#define SP5K_MEDIA_PLAY_SEEK           4
#define SP5K_MEDIA_PLAY_FORWARD        5
#define SP5K_MEDIA_PLAY_REWIND         6
#define SP5K_MEDIA_PLAY_SLOW_MOTION    7
#define SP5K_MEDIA_PLAY_FRAME_CAPTURE  8
#define SP5K_MEDIA_PLAY_RESOUCE_AVI    MEDIA_PLAY_RESOURCE_AVI/* @startAV */
#define SP5K_MEDIA_PLAY_TRIM      MEDIA_PLAY_TRIM
#define SP5K_MEDIA_PLAY_MERGE     MEDIA_PLAY_MERGE
#define SP5K_MEDIA_PLAY_SEAMLESS_EN	   MEDIA_PLAY_SEAMLESS_EN
#define SP5K_MEDIA_PLAY_SEAMLESS_LOAD  MEDIA_PLAY_SEAMLESS_LOAD
#define SP5K_MEDIA_PLAY_VIDEO_FRM_APPEND   MEDIA_PLAY_VIDEO_FRM_APPEND
#define SP5K_MEDIA_SEEK_FORWARD        15
#define SP5K_MEDIA_SEEK_BACKWARD       16



/* voice memo */
#define SP5K_MEDIA_MEMO_RECORD  ( 0x00 )
#define SP5K_MEDIA_MEMO_PLAY    ( 0x01 )
#define SP5K_MEDIA_MEMO_ABORT   ( 0x02 )
#define SP5K_MEDIA_MEMO_PAUSE   ( 0x03 )
#define SP5K_MEDIA_MEMO_RESUME  ( 0x04 )
#define SP5K_MEDIA_MEMO_SEEK    ( 0x05 )

#define SP5K_MSG_MEDIA_PARAM_OKAY  MEDIA_MSG_PARAM_OKAY
#define SP5K_MSG_MEDIA_PARAM_FAIL  MEDIA_MSG_PARAM_FAIL
#define SP5K_MSG_MEDIA_PARAM_NOHANDLE  MEDIA_MSG_PARAM_NOHANDLE

/*for seek*/
#define SEEK_FORWARD            -1
#define SEEK_BACKWARD           -2

/** media playback data source */
#define SP5K_MEDIA_PLAY_DATA_SRC_FILE   MEDIA_PLAY_DATA_SRC_FILE
#define SP5K_MEDIA_PLAY_DATA_SRC_CUSTOM MEDIA_PLAY_DATA_SRC_CUSTOM
/** media playback data type */
#define SP5K_MEDIA_PLAY_DATA_AUDIO       MEDIA_PLAY_DATA_AUDIO
#define SP5K_MEDIA_PLAY_DATA_VIDEO       MEDIA_PLAY_DATA_VIDEO




/* Selectors for setting the extra information for memo operation */
typedef enum {
	SP5K_MEDIA_MEMO_CFG_SEEK_TIME,
	SP5K_MEDIA_MEMO_CFG_FORWARD_SPEED,
	SP5K_MEDIA_MEMO_CFG_BACKWARD_SPEED,
} sp5kMediaMemoCfg_e;

/* obsolete */
#if 0
#define SP5K_MEDIA_AUDIO_EQ_NORMAL_MODE   ( 0x00 )
#define SP5K_MEDIA_AUDIO_EQ_CLASSIC_MODE  ( 0x01 )
#define SP5K_MEDIA_AUDIO_EQ_POP_MODE      ( 0x02 )
#define SP5K_MEDIA_AUDIO_EQ_BASS_MODE     ( 0x03 )
#define SP5K_MEDIA_AUDIO_EQ_ROCK_MODE     ( 0x04 )
#define SP5K_MEDIA_AUDIO_EQ_CUSTOM_MODE   ( 0x05 )
#endif

/* ALC */
typedef enum _sp5kMediaAlcParam_e {
	/** 0: disable, 1: enable ALC */
	SP5K_MEDIA_ALC_OPT                 = ALC_PARAM_ALC_OPT,

	#if SPCA6350
	/*function control*/
	SP5K_MEDIA_ALC_NOISEGATE_EN        = ALC_PARAM_NOISEGATE_EN,
	SP5K_MEDIA_ALC_ANTICLIP_EN         = ALC_PARAM_ANTICLIP_EN,
	SP5K_MEDIA_ALC_QUICKRELEASE_EN     = ALC_PARAM_QUICKRELEASE_EN,
	/*Gain Limit (GL)*/
	SP5K_MEDIA_ALC_MAX_GAIN            = ALC_PARAM_MAX_GAIN,
	SP5K_MEDIA_ALC_MIN_GAIN            = ALC_PARAM_MIN_GAIN,
	SP5K_MEDIA_ALC_NOISEGATE_MIN_GAIN  = ALC_PARAM_NOISEGATE_MIN_GAIN,

	/*Static Curve (SC)*/
	/** Base output level for input match with THD1. Also called y1 in DRC spec */
	SP5K_MEDIA_ALC_BASE_OUTPUT_VOL     = ALC_PARAM_BASE_OUTPUT_VOL,
	/** Threashold 1 for input audio level */
	SP5K_MEDIA_ALC_THD1                = ALC_PARAM_THD1,
	/** Threashold 2 for input audio level */
	SP5K_MEDIA_ALC_THD2                = ALC_PARAM_THD2,
	/** Threashold 3 for input audio level */
	SP5K_MEDIA_ALC_THD3                = ALC_PARAM_THD3,
	/** Threashold 4 for input audio level */
	SP5K_MEDIA_ALC_THD4                = ALC_PARAM_THD4,
	/** Threashold 5 for input audio level */
	SP5K_MEDIA_ALC_THD5                = ALC_PARAM_THD5,
	/** Slop 1: between 0db ~ THD1 */
	SP5K_MEDIA_ALC_SLOP1               = ALC_PARAM_SLOP1,
	/** Slop 2: between THD1 ~ THD2 */
	SP5K_MEDIA_ALC_SLOP2               = ALC_PARAM_SLOP2,
	/** Slop 3: between THD2 ~ THD3 */
	SP5K_MEDIA_ALC_SLOP3               = ALC_PARAM_SLOP3,
	/** Slop 4: between THD3 ~ THD4 */
	SP5K_MEDIA_ALC_SLOP4               = ALC_PARAM_SLOP4,
	/** Slop 5: between THD4 ~ THD5 */
	SP5K_MEDIA_ALC_SLOP5               = ALC_PARAM_SLOP5,
	/** Slop 6: for input data < THD5. Also called Noise Gate area. */
	SP5K_MEDIA_ALC_SLOP6               = ALC_PARAM_SLOP6,
	/*Level Measurement (LM)*/
	SP5K_MEDIA_ALC_LM_ATTACK_TIME      = ALC_PARAM_LM_ATTACK_TIME,
	SP5K_MEDIA_ALC_LM_RELEASE_TIME     = ALC_PARAM_LM_RELEASE_TIME,
	SP5K_MEDIA_ALC_LM_AVG_TIME         = ALC_PARAM_LM_AVG_TIME,
	/*Gain Smooth (GS)*/
	SP5K_MEDIA_ALC_GS_DECAY_TIME       = ALC_PARAM_GS_DECAY_TIME,
	SP5K_MEDIA_ALC_GS_ATTACK_TIME      = ALC_PARAM_GS_ATTACK_TIME,
	/* SW ALC control PGA */
	SP5K_MEDIA_ALC_PARAM_MAX_VOL_DB    = ALC_PARAM_MAX_VOL_DB,
	SP5K_MEDIA_ALC_PARAM_HOLD_TIME_MS  = ALC_PARAM_HOLD_TIME_MS,
	SP5K_MEDIA_ALC_CUR_ENERGY          = ALC_PARAM_ALC_CUR_ENGENY,

	#elif SPCA6330
	/** not used */
	SP5K_MEDIA_ALC_WIN_SIZE            = ALC_PARAM_ALC_WIN_SIZE,
	/** max gain index, 0 ~ 43, +1.5dB each step ; 0 ~ 50, 3dB each step for 5330 */
	SP5K_MEDIA_ALC_MAX_GAIN_IDX        = ALC_PARAM_ALC_MAX_GAIN_IDX,
	/** min gain index, 0 ~ 43, +1.5dB each step ; 0 ~ 50, 3dB each step for 5330 */
	SP5K_MEDIA_ALC_MIN_GAIN_IDX        = ALC_PARAM_ALC_MIN_GAIN_IDX,
	/** max rms in one frame */
	SP5K_MEDIA_ALC_MAX_VOL             = ALC_PARAM_ALC_MAX_VOL,
	/** min rms in one frame */
	SP5K_MEDIA_ALC_MIN_VOL             = ALC_PARAM_ALC_MIN_VOL,
	/** default gain index, 0 ~ 43, +1.5dB each step ; 0 ~ 50, 3dB each step for 5330 */
	SP5K_MEDIA_ALC_DEFAULT_GAIN_IDX    = ALC_PARAM_ALC_DEFAULT_GAIN_IDX,
	/** frame count to tune up gain */
	SP5K_MEDIA_ALC_GAIN_UP_SPEED       = ALC_PARAM_ALC_GAIN_UP_SPEED,
	/** frame count to tune down gain */
	SP5K_MEDIA_ALC_GAIN_DOWN_SPEED     = ALC_PARAM_ALC_GAIN_DOWN_SPEED,
	/** max audio volume gap */
	SP5K_MEDIA_ALC_MAX_VOL_GAP         = ALC_PARAM_ALC_MAX_VOL_GAP,
	/** frame count to tune down gain in silence state */
	SP5K_MEDIA_SILENCE_GAIN_DOWN_SPEED = ALC_PARAM_SILENCE_GAIN_DOWN_SPEED,
	/** The increase value of audio gain */
	SP5K_MEDIA_ALC_GAIN_UP_STEP        = ALC_PARAM_ALC_GAIN_UP_STEP,
	/** The decrease value of audio gain */
	SP5K_MEDIA_ALC_GAIN_DOWN_STEP      = ALC_PARAM_ALC_GAIN_DOWN_STEP,
	/** [31]: slience, [27:0]: value */
	SP5K_MEDIA_ALC_CUR_ENERGY          = ALC_PARAM_ALC_CUR_ENGENY,
	#endif

	SP5K_MEDIA_ALC_MAX                 = ALC_PARAM_ALC_MAX,
} sp5kMediaAlcParam_e;

/**
 * \note
 * scale down media thumbnail with the specified factor
 * para: scale down factor, range from 1000 (1x) to 100 (0.1x)
 */
#define SP5K_MEDIA_PLAY_THUMB_SCALE		MEDIA_PLAY_THUMB_SCALE
/**
 * \note
 * set background color if scaling down media thumbnail is set
 * para: color in RGB565 format
 */
#define SP5K_MEDIA_PLAY_THUMB_BGCOLOR	MEDIA_PLAY_THUMB_BGCOLOR
/**
 * \note
 * enable/disable background frame blending to media thumbnail
 * para: 0:disable background frame, 1:enable
 */
#define SP5K_MEDIA_PLAY_THUMB_BGFRAME	MEDIA_PLAY_THUMB_BGFRAME
/**
 * \note
 * for background frame blending, if y value in background frame is
 * less than the input threshold, the pixel will be treated as
 * color key
 * para: y threahold (0~255)
 */
#define SP5K_MEDIA_PLAY_THUMB_COLORKEY	MEDIA_PLAY_THUMB_COLORKEY
/**
 * \note
 * for skip the display of video thumbnail.
 * para: 0: disable skip, 1: skip.
 */
#define SP5K_MEDIA_PLAY_THUMB_SKIP      MEDIA_PLAY_THUMB_SKIP

/**
 * \note
 * file name of background frame which blending to media thumbnail.
 * para: background frame file name.
 */
#define SP5K_MEDIA_PLAY_THUMB_BGFRAME_FILENAME      MEDIA_PLAY_THUMB_BGFRAME_FILENAME


/* selector of channel for ALC parameter*/
typedef enum _sp5kMediaRecAlcChnl_e {
	SP5K_MEDIA_REC_ALC_CH_LEFT  = 1,
	SP5K_MEDIA_REC_ALC_CH_RIGHT = 2,
	SP5K_MEDIA_REC_ALC_CH_ALL   = 3,
} sp5kMediaRecAlcChnl_e;  /* direct map to audRecChnl_e. */

/* ALC mode selector of cfgid SP5K_MEDIA_REC_ALC_MODE in sp5kMediaRecCfgSet */
#define SP5K_MEDIA_REC_ALC_CST_MODE  MEDIA_REC_ALC_CST_MODE
#define SP5K_MEDIA_REC_ALC_DRC_MODE  MEDIA_REC_ALC_DRC_MODE
#define SP5K_MEDIA_REC_ALC_DRC_PGA_MODE		MEDIA_REC_ALC_DRC_PGA_MODE

/* media edit */
#define SP5K_MEDIA_EDIT_TRIM  MEDIA_EDIT_TRIM

/**************************************************************************
 *                          D A T A    T Y P E S                          *
 **************************************************************************/
/** @brief SP5K_MEDIA_REC_DIS_COMPENSATE_CALC_CB Customer Cb - dist compensate offset calculate information */
#define sp5kDistCompensateCalcCbEx_t    distCompensateCalcCbEx_t

/** @brief SP5K_MEDIA_REC_DIS_GMV_CALC_CB Customer Cb - dist GMV calculate information */
#define sp5kDistGmvCalcCbEx_t       distGmvCalcCbEx_t

#define sp5kMediaStreamAttr_t mediaAttrVal_t


/*For SP5K_MEDIA_REC_H264_SEI_CB_INIT_CB*/
typedef struct{
	void* ppayload;/*Payload data whose data structure is depend on payload type.*/
	UINT32 status;/*to control the behavior of this object.*/
} sp5k_media_h264_sei_obj_t;

typedef struct{
	UINT32 streamId;
	UINT32 frameNum;
	UINT32 sliceType;
} sp5k_media_h264_sei_Info_t;

typedef struct{
	UINT32 objNum;/*SEI obj total*/
	sp5k_media_h264_sei_obj_t **ppobj;/*pointer to a array of pointer to SEI obj*/
	UINT32 (*pfn)(const sp5k_media_h264_sei_Info_t*, sp5k_media_h264_sei_obj_t*); /*for host to update SEI*/
} sp5k_media_h264_sei_cb_t;


/*For SEI*/
#define SP5k_COMMON_SEI_ELEMENT \
	const UINT32 payloadType; \
	UINT32 payloadSize;

typedef struct{
	SP5k_COMMON_SEI_ELEMENT
} sp5k_common_sei_element_t;

typedef struct{
	SP5k_COMMON_SEI_ELEMENT
	UINT8* ppayloadData;	/*[0:15] uuid, u(128), [16:N] payload data, b(8)*/
} sp5k_unreg_user_data_sei_element_t;

/**************************************************************************
 *               F U N C T I O N    D E C L A R A T I O N S
 **************************************************************************/
/* sp5k_media_api.c */
UINT32 sp5kMediaCfgSet(UINT32 cfgId, UINT32 value);
UINT32 sp5kMediaCfgGet(UINT32 cfgId, UINT32 *pvalue);
UINT32 sp5kMediaRecCfgSet(UINT32 cfgId, UINT32 value);
UINT32 sp5kMediaRecCfgGet(UINT32 cfgId, UINT32 *pvalue);
UINT32 sp5kMediaRecControl(UINT32 option, ...);
UINT32 sp5kMediaRecStreamSet(UINT32 streamId, sp5kMediaStreamAttr_t *pattr);
UINT32 sp5kMediaPlayControl(UINT32 option, UINT32 param1, UINT32 param2);
UINT32 sp5kMediaPlayAttrParse(void);
UINT32 sp5kMediaRecAttrSet(UINT32 attrId, UINT32 value, ...);
UINT32 sp5kMediaRecAttrGet(UINT32 attrId, UINT32 *pvalue);
UINT32 sp5kMediaPlayCfgSet(UINT32 cfgId, UINT32 value);
UINT32 sp5kMediaPlayCfgGet(UINT32 cfgId, UINT32 *pvalue);
UINT32 sp5kMediaPlayAttrGet(UINT32 attrId, UINT32 *pvalue);
UINT32 sp5kMediaMemoControl(UINT32 dcfIdx, UINT32 control);
UINT32 sp5kMediaMemoCfgSet(UINT32 selector, void *value);
UINT32 sp5kMediaPlayThumbCfgSet(UINT32 cfgId, UINT32 value);
UINT32 sp5kMediaRecAviChunkSet(mediaAviChunk_e chunk, UINT8 *pbuf, UINT32 size);
UINT32 sp5kMediaPlayAviChunkInfoGet(mediaAviChunk_e chunk, UINT32 *poffset, UINT32 *psize);
UINT32 sp5kMediaPlayAviChunkBufSet(mediaAviChunk_e chunk, UINT8 *pbuf, UINT32 size);
UINT32 sp5kMediaRecAviChunkUpdate(mediaAviChunk_e chunk, UINT32 offset, UINT32 size, UINT8 *pbuf);
UINT32 sp5kMediaRecWavInfoSet(UINT8 *pbuf, UINT32 size);
UINT32 sp5kMediaPlayWavInfoBufSet(UINT8 *pbuf, UINT32 size);
UINT32 sp5kMediaPlayImgWinSet(UINT32 x, UINT32 y, UINT32 w, UINT32 h);
UINT32 sp5kMediaAlcParamSet(UINT32 chnlId, UINT32 attrId, UINT32 value);
UINT32 sp5kMediaAlcParamGet(UINT32 chnlId, UINT32 attrId, UINT32 *pvalue);
UINT32 sp5kMediaPlayAttrSet(UINT32 attrId, UINT32 value);
UINT32 sp5kMediaAlcParamFileLoad(UINT8 *pfileName);
UINT32 sp5kMediaRecUserDataUpdate(UINT8 *psrc, UINT32 size, UINT32 offset, UINT32 append);
UINT32 sp5kMediaRecInfoQuery(UINT8* pQuery, UINT32* pType, UINT32* pData, UINT32* pSize);
UINT32 sp5kMediaDelete(UINT8 *fileName,UINT32 fileType,UINT32 para, ...);
UINT32 sp5kMediaPlayDataSend(UINT32 dataType, UINT8 *pdata,UINT32 size, UINT32 pts);


#endif /* _SP5K_MEDIA_API_H_ */

