
#ifndef _APP_INFOHANDLER_H_
#define _APP_INFOHANDLER_H_
#include "app_infohandlerComm.h"

/*INFO STATUS*/
#define  INFO_STATUS_CHECKSUM_ERR 0x01

/*INFO Header case*/
#define  INFO_HEADERLEN 5

#define  INFO_HEADER_ERR 0x00
#define  INFO_HEADER_CMD 0x01
#define  INFO_HEADER_MSG 0x02
/*INFO NUM*/
#define INFO_HEADERNUM_START 5
#define INFO_HEADERNUM_LEN 3

#define	INFO_HEADERNUM_DEVINFO 1
#define	INFO_HEADERNUM_SETOPTMODE 2
#define	INFO_HEADERNUM_DEVFWVER 3
#define	INFO_HEADERNUM_DISKINFO 4
#define	INFO_HEADERNUM_SDFORMAT 5
#define	INFO_HEADERNUM_SETSNAPMARK 7
#define	INFO_HEADERNUM_DISKERRINFO 10
#define	INFO_HEADERNUM_STARTUSRTRIGGEREVENT 11
#define	INFO_HEADERNUM_FILECOUNT 12
#define	INFO_HEADERNUM_FILELIST 13
#define	INFO_HEADERNUM_FILEINFO 14
#define	INFO_HEADERNUM_FILEDEL 15
#define	INFO_HEADERNUM_FILEPLAYBAKSTART 16
#define	INFO_HEADERNUM_FILEPLAYBAKSTOP 17
#define	INFO_HEADERNUM_FILEPLAYBAKPAUSE 18
#define	INFO_HEADERNUM_SETRES 20
#define	INFO_HEADERNUM_SETFACTORYREST 23
#define	INFO_HEADERNUM_SDNUMTIME 24
#define	INFO_HEADERNUM_SCANSD 25
#define	INFO_HEADERNUM_SDFORMATNECESSITY 26
#define INFO_HEADERNUM_HITEMPPROTECTED 32
#define	INFO_HEADERNUM_SDPLUGINOUT 33
#define	INFO_HEADERNUM_ACAILABLESPACE 35
#define	INFO_HEADERNUM_WRITEENDURANCE 36
#define	INFO_HEADERNUM_STOPUSRTRIGGEREVENT 37
#define	INFO_HEADERNUM_MOVEFILESVAEFOLDER 38
#define	INFO_HEADERNUM_FORMATOK 40
#define	INFO_HEADERNUM_ANNOUNCECONNECTDEV 44
#define	INFO_HEADERNUM_REGULARCOM 45
#define	INFO_HEADERNUM_ERRORSTATUSINFO 46
#define	INFO_HEADERNUM_SETGSENSOR 50
#define	INFO_HEADERNUM_SETGSENSORCALIBRATION 51
#define	INFO_HEADERNUM_SETBEEPSOUND 52
#define	INFO_HEADERNUM_SETRECORDER 53
#define	INFO_HEADERNUM_SETPARKMODE 55
#define	INFO_HEADERNUM_SETASSISTMODE 56
#define	INFO_HEADERNUM_REQPOSITIONMSG 100
#define	INFO_HEADERNUM_PLAYPOSITIONMSG 101
#define INFO_HEADERNUM_GETSETTINGVALUE 998
#define	INFO_HEADERNUM_SDLOGSET 999



#define INFO_SETOPTMODE_NONE 0x00
#define INFO_SETOPTMODE_PRE    0x01
#define INFO_SETOPTMODE_REC    0x02
#define INFO_SETOPTMODE_PLAY_IDLE    0x03
#define INFO_SETOPTMODE_PLAYING    0x04



extern void appInfoiStateToPState(UINT32 iState);

extern void appInfoPanaStateSet(PanaState state);

extern RECState appInfoRECStateGet(void);

#endif /* _APP_INFOHANDLER_H_ */

